### ISSUE TITLE
Supabase Functions Redirect Doesn't Redirect

### ISSUE THREAD

**Issue by michaelrkn** [supabase/supabase#10325]
# Bug report

## Describe the bug

`return Response.redirect` from a Supabase function renders the target URL instead of returning the appropriate redirect.

## To Reproduce

Use the [Deno example](https://deno.com/deploy/docs/examples#redirect). Open in Editor to save yourself time. My example was deployed to https://thirsty-hedgehog-40.deno.dev. It properly redirects to example.com

Now, create a Supabase project and generate a function. Copy the same code in. Deploy it (with the `--no-verify-jwt` flag). Mine is deployed to https://uxcjzomklsrmofrcvnwh.functions.supabase.co/redirect. It displays the HTML for example.com.

## Expected behavior

The Supabase function should return a 307 redirect to example.com.

**Comment by laktek** [comment]
Hey @michaelrkn, we just deployed a fix for it. Can you try again?

We have also added an example using Oak on how to make a redirect https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/oak-server/index.ts#L17-L19

**Comment by michaelrkn** [comment]
Seems to work, thank you!

**Comment by sloba88** [comment]
I still have the same issue.

`context.response.redirect("https://google.com")` returns plain HTML instead of redirecting 

```
supabase --version
1.49.4

"oak": "https://deno.land/x/oak@v12.1.0/mod.ts"

What do I need to upgrade to make this work? @laktek

**Comment by sloba88** [comment]
The root of the problem is that it's not possible to return HTML at all. I've tested this with a plain deno server and it works. Running it via Supabase functions returns text/plain.

**Comment by rohankm** [comment]
> The root of the problem is that it's not possible to return HTML at all. I've tested this with a plain deno server and it works. Running it via Supabase functions returns text/plain.

any solution for this?

**Comment by udrzbarik** [comment]
I think they said in a post that it's not what Edge Functions are intended for (serving SSG content). But would definitely be a nice to have.
