### ISSUE TITLE
Vercel integration not working

### ISSUE THREAD

**Issue by oplotDev** [supabase/supabase#10399]
i tried to add supabase integration to my vercel deploy, but in "Vercel" "Choose a project" don't have any my deploy

![image](https://user-images.githubusercontent.com/106649669/202678309-92d28841-3af8-421d-bec4-51bbec979b3d.png)

**Comment by Hallidayo** [comment]
Hi @oplotDev - Have you followed all the steps in this [guide](https://supabase.com/docs/guides/integrations/vercel)?

**Comment by oplotDev** [comment]
yes

**Comment by oplotDev** [comment]
after i click the "Add integration" me redirects to my supabase projects (https://app.supabase.com/projects)

**Comment by nabilfatih** [comment]
I didnt even get a pop like you... after i click add integration from vercel, it just redirects me to my supabase projects (https://app.supabase.com/projects) and do absolutely nothing. 

Please fix this immediately, really need this integration :(

**Comment by AndreVarandas** [comment]
I'm experiencing the same issue when setting up from [https://github.com/vercel/nextjs-subscription-payments](https://github.com/vercel/nextjs-subscription-payments) - When I click on the add integration button, I'm redirected to the dashboard.

**Comment by oplotDev** [comment]
fixed

**Comment by ragone** [comment]
This is still an issue :(

**Comment by ydoc5212** [comment]
bug still happening! takes me back to my supabase dashboard upon logging into supabase. the problem seems to be on supabase's end. i tried in incognito--still happening.
