### ISSUE TITLE
Studio Storage page: This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by itisnajim** [supabase/supabase#11136]
# Bug report

## Describe the bug
after cloning the repo, starting the docker, and setting up everything,
this error will appear when trying to open the studio storage page 
```
Mixed Content: The page at 'https://supabase.example.com/project/default/storage/buckets'
was loaded over HTTPS, but requested an insecure resource 
'http://supabase.example.com/storage/v1/bucket'. This request has been blocked; the content
must be served over HTTPS.
```
## To Reproduce
open the link: https://supabase.example.com/project/default/storage/buckets
or via the left side menu click on the storage icon button.
and then you will see an error indicate the the fetch failed.

## A way to solve
i solved this by adding `add_header Content-Security-Policy "upgrade-insecure-requests";` to the nginx server block, under location /

```nginx
location / {
 ...
}
add_header Content-Security-Policy "upgrade-insecure-requests";
```

**Comment by globemediaofficial** [comment]
> ```nginx
> location / {
>  ...
> }
> add_header Content-Security-Policy "upgrade-insecure-requests";
> ```

@itisnajim 
This didn't fix the issue for me. Can you post a full version of what the `Nginx` config should look like with this line added?

**Comment by itisnajim** [comment]
I'm not at my computer right now, I'm guessing maybe because the chrome cache 

Right-click and choose Inspect Element to open the DevTools. Or use one of the following keyboard shortcuts:
F12
Control+Shift+i
Command+Shift+i
Click Network in the toolbar to open the network pane.
Check the Disable cache checkbox at the top.

Then reload the page without closing the inspector

**Comment by globemediaofficial** [comment]
Unfortunately the cache wasn't the issue. I even tried on different browsers with no luck. There is definitely a bug that uses the `http` link instead of `https` so I guess I'll just have to wait for that to be fixed. I think `Nginx` is not working for me because I use a `Cloudflare Tunnel` to reach the studio and kong instead of `Nginx`.

**Comment by mingfang** [comment]
I traced the problem to here
https://github.com/supabase/supabase/blob/a0763d8ca87753b0c82c8d9ded2d14a343940eaf/studio/localStores/storageExplorer/StorageExplorerStore.js#L121

`PROJECT_ENDPOINT_PROTOCOL` has the value of `http`.

My guess is this part of the code is executed entirely on the browser and not rendered on the server, and as a result this code
https://github.com/supabase/supabase/blob/a0763d8ca87753b0c82c8d9ded2d14a343940eaf/studio/pages/api/constants.ts#L1
has no access to `process.env.SUPABASE_PUBLIC_URL`, and resulted to using the value `http://localhost:8000`.

One solution would be to somehow pass the correct URL when calling  `useStorageStore(url)`

**Comment by mingfang** [comment]
the problem was introduced by this commit https://github.com/supabase/supabase/commit/0868ee96f27333cd541dd5d512368a584a510210

**Comment by globemediaofficial** [comment]
@mingfang 
I found the origin of the issue a couple days ago and finally figured out how to fix it. I've never worked with these coding languages so that's why it took a while. I created a PR which will likely be accepted and will fix the error.

**Comment by alaister** [comment]
@globemediaofficial's fix has been merged 🎉

I can no longer produce the issue, so I'm going to close this. Please feel free to reopen it if the issue is persisting after pulling down the latest version of `master`.

**Comment by prodkt** [comment]
Multiple tried on multiple devices, this is still happening on fresh inits of supabase localhost containers.

**Comment by KloudCoder** [comment]
> Multiple tried on multiple devices, this is still happening on fresh inits of supabase localhost containers.

Same here. I setup supabase on a k8s cluster and setup tls for studio and kong. Now trying to add a user in the db through the studio results in a Mixed content error.

**Comment by MRzsztk** [comment]
I think this is still an issue, using the newest chart from bitnami (2.8.1) and I'm stumbling upon the error mentioned by KloudCoder

**Comment by RaisHelmy97** [comment]
same issue until 7 dec 2024

**Comment by refeals** [comment]
also happening for me on a VPS

**Comment by morandalex** [comment]
i see that issue now ...

when i load a file over 6.5 mb i see as follwo in console

Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.


in my .env  config i have FILE_SIZE_LIMIT=100000000

<img width="427" height="29" alt="Image" src="https://github.com/user-attachments/assets/bfeb2356-5667-4fa2-9425-937938a6e453" />
