### ISSUE TITLE
FATAL : unsupported frontend protocol 0.0: server supports 3.0 to 3.0

### ISSUE THREAD

**Issue by alex-galey** [supabase/supabase#12436]
# Bug report

## Describe the bug

FATAL errors in postgres logs from time to time, these two are triggered at the same time :
unsupported frontend protocol 0.0: server supports 3.0 to 3.0
unsupported frontend protocol 255.255: server supports 3.0 to 3.0

I don't know if it is related to this other issue : https://github.com/supabase/supabase/issues/12435

```
{
  "file": "/var/log/postgresql/postgresql.csv",
  "host": "db-***",
  "metadata": [],
  "parsed": [
    {
      "application_name": null,
      "backend_type": "not initialized",
      "command_tag": null,
      "connection_from": "***.221:60716",
      "context": null,
      "database_name": null,
      "detail": null,
      "error_severity": "FATAL",
      "hint": null,
      "internal_query": null,
      "internal_query_pos": null,
      "leader_pid": null,
      "location": null,
      "process_id": 260065,
      "query": null,
      "query_id": 0,
      "query_pos": null,
      "session_id": "***",
      "session_line_num": 2,
      "session_start_time": "2023-02-14 08:26:07 UTC",
      "sql_state_code": "0A000",
      "timestamp": "2023-02-14 08:26:07.737 UTC",
      "transaction_id": 0,
      "user_name": null,
      "virtual_transaction_id": null
    }
  ],
  "parsed_from": null,
  "project": "***",
  "source_type": "file"
}
```
## To Reproduce

I don't know how to reproduce but you can see it on the project

## Expected behavior

No fatal error or error not being fatal if it's not an issue

## System information

Supabase cloud

**Comment by jopfre** [comment]
I have the same issue

**Comment by bangdragon** [comment]
I have this error today

**Comment by Pertoldi** [comment]
This error come in pair with the one on https://github.com/supabase/supabase/issues/12435.
After some research I found this: https://pganalyze.com/docs/log-insights/connections/C31
> This error message indicates that the client requested a Postgres FE/BE protocol version that the server does not support.

> The most likely explanation for this is programs accidentally connecting to the Postgres port and not writing the correct protocol > structure. **You may also see this when someone runs a port scanner against your database server**.

Effectively, I can observe some connection that are not intended.
They lok like this
```bash
LOG connection received: host=71.6.134.233 port=36540
...
LOG connection received: host=71.6.134.233 port=36534
```

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!

**Comment by LuKrO2011** [comment]
As far as I can tell, the issue still persists. My log at 21/02/2024 19:10:10:
[DATABASE] [9-1] sql_error_code = 0A000 time_ms = "2024-02-21 18:10:10.239 UTC" pid="184378" proc_start_time="2024-02-21 18:10:09 UTC" session_id="..." vtid="" tid="0" log_line="2" database="[unknown]" connection_source="..." user="[unknown]" application_name="[unknown]" FATAL: unsupported frontend protocol 0.0: server supports 3.0 to 3.0

**Comment by encima** [comment]
@LuKrO2011 
- How are you connecting to Postgres?
- Are you connecting directly to the database or using the pooler?
- Have you configured SSL?

**Comment by LuKrO2011** [comment]
The spring application is hosted on Heroku. I use their [SSL](https://devcenter.heroku.com/articles/connecting-heroku-postgres).
The database configuration is as follows:
```
@Configuration
public class DatabaseConfig {

    @Value("${spring.datasource.url}")
    private String dbUrl;

    @Bean
    public DataSource dataSource() {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(dbUrl);
        return new HikariDataSource(config);
    }
}
```

I further specified in the application.yaml file:
```
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
```

**Comment by encima** [comment]
@LuKrO2011 That is likely an issue with the JDBC driver being used. Does the issue occur with other Postgres databases as well? Make sure the version supports your database version
