### ISSUE TITLE
Cannot sign in with signInWithPassword

### ISSUE THREAD

**Issue by HeartSentinel** [supabase/supabase#12724]
## Describe the bug

Suddenly for the past few hours you can't log in with our App, which has been published for a couple of months.

Using signInWithPassword the result we get is:

![image](https://user-images.githubusercontent.com/107626917/221908157-5a34a065-5014-437d-8f23-fdfbd692b880.png)

## To Reproduce

  import { createClient } from "@supabase/supabase-js";

  // 1. create client with public key
  const supabase = createClient(
    "https://lkbyvmfrupnaygjstjhr.supabase.co",
    "anon_public_key"
  );

  // 2. sign in member
  const { data, error } = await supabase.auth.signInWithPassword({
    email: "heartsentinel.it@gmail.com",
    password: "<pw>",
  });

## System information

- OS: Android, iOS, Windows
- Browser: Chrome, Safari
- Version of @supabase/supabase-js: 2.8.0
- Angular 14 and 15
- Ionic 6

**Comment by KajSzy** [comment]
I've same issue on my project `https://lorwbruuywvxipcvutmw.supabase.co`
Using both password auth and google oauth throws such error.
The issue started to occur about 11 GMT 28th Feb.

**Comment by QuentR** [comment]
Same issue here. Password auth doesn't work anymore for about one hour

**Comment by tzhf** [comment]
Same here, using Twitch provider.

**Comment by kolagrey** [comment]
Same issue here. Auth hasn't been working for over 3hrs now

**Comment by GaryAustin1** [comment]
https://discord.com/channels/839993398554656828/1006358244786196510/threads/1080091430443307059
A couple of different users (I think) reporting same issue in Discord

**Comment by AdriMsM91** [comment]
Hello, same issue here, we can't even log in for the last 6h.

**Comment by GaryAustin1** [comment]
![image](https://user-images.githubusercontent.com/54564956/221936240-2d715373-9152-4805-b2c6-8b54ef37f672.png)
Just added to status page

**Comment by franfernandez20** [comment]
Hi, same for us. We are experiencing the same issue at project ´danujfghrppifxfvfnwm´

**Comment by JSmithOner** [comment]
same issue.Thanks in advance for your support.

**Comment by pucke-uninow** [comment]
Same here, using google provider.

**Comment by KajSzy** [comment]
Isssue seems to be fixed on my project

**Comment by HeartSentinel** [comment]
The problem has been solved.

![Immagine WhatsApp 2023-02-28 ore 20 23 16](https://user-images.githubusercontent.com/107626917/222058180-94dbece7-3e4d-400a-85dc-0da1a5be09a9.jpg)

**Comment by ZhenFTW** [comment]
Hello I know it's been closed but I'm still having issue as of today. My region is ap-southeast-1.

**Comment by kbsali** [comment]
Same here in `eu-west-1` :(

**Comment by jnorris441** [comment]
still happening us-west-1

**Comment by kbsali** [comment]
As mentioned in #12741 a few of us got an answer from the support saying : 
```
Hey Kevin​,

Thank you for contacting Supabase Support. Recently we had to modify the type of the `phone` and `phone_change` columns in `auth.users` which requires any triggers or views dependent on those columns to be recreated. You can fix this problem by recreating (dropping then adding again) the triggers that were using these columns.
```
