### ISSUE TITLE
Auth documentation examples do not work

### ISSUE THREAD

**Issue by malobre** [supabase/supabase#133]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository
- [ ] question about how to use this project

* **Summary**
On https://supabase.io/docs/library/user-management/ the examples for `signup(..)` and `login(..)` are shown to use an object containing an `email` and `password` field as argument but this doesn't work. The object is passed along as if it was an email and the auth request is sent with the following data:
```json
{
  "email": {
    "email": "someone@email.com",
    "password": "password"
  }
}
```

* **Other information**
```
└─┬ @supabase/supabase-js@0.35.10
  ├── @supabase/doctest-js@0.1.0
  ├── @supabase/postgrest-js@0.17.0
  └── @supabase/realtime-js@0.9.0
```

**Comment by awalias** [comment]
thanks for catching: fixed here 76416bc69bebd4113644861cde86675acad25c24

should be live any minute now

**Comment by malobre** [comment]
Well that was fast, but you forgot to remove the names of the object field :)

**Comment by awalias** [comment]
haha too fast @malobre 70968af9609af5a1924254668ac525662d9590de
