### ISSUE TITLE
Running query in SQL editor shows result from previously run query

### ISSUE THREAD

**Issue by lovisaberggren** [supabase/supabase#13717]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running a query in the SQL editor, the results shown corresponds to the last run query. The query needs to be run two times to get the correct result. This causes uncertainties whether a query was completed or not. I have not had this issue until today (14 April 2023).

## To Reproduce

You need two or more saved query snippets.

1. Go to SQL editor in dashboard
2. Click on a snippet and run
3. Go to another snippet and run, the result will be the same as in 2.
4. Run second snippet again, now the result will be different.

## Expected behavior

I expect the result to show the correct result of the query which is executed.

## Screenshots

Run query one (correct):
<img width="1129" alt="Screenshot 2023-04-14 at 11 46 47" src="https://user-images.githubusercontent.com/59226031/232010662-e4298782-8f10-4a8d-9d00-8693cca7d8d3.png">

Run query 2 in another saved snippet (wrong):
<img width="1127" alt="Screenshot 2023-04-14 at 11 47 07" src="https://user-images.githubusercontent.com/59226031/232010670-8a11c76f-2b54-4cc4-a1db-a84caf6fa515.png">

Run query 2 a second time (correct):
<img width="1124" alt="Screenshot 2023-04-14 at 11 47 15" src="https://user-images.githubusercontent.com/59226031/232010674-20982193-8882-472e-86b3-3ec15ec3c8a7.png">

## System information

- OS:  macOS
- Browser: Safari

**Comment by wizzymotion** [comment]
I'm facing the same Bug here.

- OS: macOS
- Browser: Chrome

**Comment by gabrielsestrem** [comment]
GUYS! My SQL queries are a completely mess!!! Commands I run it’s bringing other results and all my queries where ordered from A-Z now it’s not sorted. I do have 100+ queries and I cannot work in this current state

Incan confirm this issue it's true!

**Comment by mlanza** [comment]
Imagine the accidents which could result from running the SQL of a previously opened snippet, thinking you are going to run the newly selected one.  This was not always the case, so something changed.  I was on a 2 month hiatus and only returned to Supabase work.  I don't recall it happening before then.

But here's the issue:

You are continually editing and jumping between various saved snippets.  And running them.  You switch from snippet A to B and click run, you end up running A but intend to run B.  If you click run again it does run B.

I also noticed if you make an edit to the snippet and run, it appears to somehow commit the update to the snippet when clicking run.  It does not actually execute it.  But then, if you click run again, after the edit was saved (from the prior run click, it seems), then it runs the snippet.

It's workable and I've gotten used to the weirdness, but it's awkward.

**Comment by gabrielsestrem** [comment]
For me it's not even workable because I can't find the snipped properly as I have so many snippets. Luckily enough all my snippets are select statements, so no big deal.

**Comment by Svengineering** [comment]
I'm experiencing the same. ***This is very severe.***
I'm developing a project, but I accidentally dropped a table.
 
I had to make a key unique and because no other solution worked (truncating was not enough) I dropped the table with the SQL editor on purpose. Then I re-created the table with the unique constraint on one column, filled it. Then I made a new query in the query editor, and ... the table was dropped cause it was executing the previous statement.

**Comment by MildTomato** [comment]
> I'm experiencing the same. This is very severe.

Hey folks - Looking at reproducing this now. Checking severance of issue

**Comment by inian** [comment]
We have declared an incident here https://status.supabase.com/incidents/7gzwd8hz76b7

**Comment by joshenlim** [comment]
hey all! apologies about this - and thanks so much for reporting this issue! We've pushed out a fix for this, please do refresh your browser and try again, if anything goes wrong please let us know anytime!

**Comment by mlynch** [comment]
Yea I'm still seeing strange behavior in the SQL editor. For example, deleting a query still shows the query in the left hand side, and the contents are still accessible, but if I try to delete it I get an error that it may have already been deleted.
