### ISSUE TITLE
Supabase auth (google) not working properly

### ISSUE THREAD

**Issue by ibrahimkholil6210** [supabase/supabase#15930]
# Bug report

## Describe the bug

I've implement the supabase auth with google provider in a create-react-app enviroment. Now when i go through the signin process it redirects me to localhost with token instade of signin me in.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Bootstrap CRA and implement supabase auth

## Screenshots

<img width="830" alt="Screenshot 2023-07-20 at 8 46 37 PM" src="https://github.com/supabase/supabase/assets/33357137/2e07a0dd-55bd-4946-810f-5a4f4c5ff808">

Initial Page

<img width="837" alt="Screenshot 2023-07-20 at 8 47 02 PM" src="https://github.com/supabase/supabase/assets/33357137/d19044d2-491e-44dd-a0a1-ad315af588f2">

This is after is signed in with, it just sent me session information in url hast. But doesn't actually log me in.

<img width="759" alt="Screenshot 2023-07-20 at 8 40 17 PM" src="https://github.com/supabase/supabase/assets/33357137/3da7ffbf-7d2f-40ff-a8e8-71b086c4a856">

I'm trying to get the user session but it doesn't returns anything.

## System information

- OS: masOs
- Browser chrome
- Version of supabase-js: 2.26.0
- Version of Node.js: v20.3.1

One thing i've tried the same with Nextjs it worked fine. I'm not sure what is the issue here.

**Comment by mallahyari** [comment]
I have had the same problem. My app stopped working since last night. It shows a blank page when redirecting from google. However, when I use Firefox and open dev tools it works. it's so weird.

**Comment by j4w8n** [comment]
Possibly related. Or just a coincidence.

https://github.com/supabase/supabase-js/issues/811

**Comment by yeonjulee1005** [comment]
I have a same error
Not only google OAuth, but also another OAuth (kakao, apple, discord, google)
After OAuth process, it just return url, no return user authenticate data🥲

**Comment by egemenu** [comment]
I agree with @mallahyari, works on Firefox but not Chrome, weird.

**Comment by GaryAustin1** [comment]
Not really up on this but... You mention works on Firefox and not Chrome.  Is it possible you were running on Chrome, upgraded, or got upgraded and then it stopped.  Then went to Firefox with the "new versions" or a clean slate?   Maybe some local storage/cookie thing from an old version to new?   Just speculating.

**Comment by mallahyari** [comment]
It was working. But all of a sudden since last night it stopped. I haven't updated Chrome or Firefox last couple of days. I even tested on Safari and Edge and it doesn't work, the same blank page appears. Even in Firefox, you have open "dev tools" otherwise it doesn't work. That's weird and frustrating, because my whole app depends on it. I am looking to replace Supabase with another platform.

**Comment by GaryAustin1** [comment]
@mallahyari that is more detail... I was mainly thinking along the lines of the supabase code updating and why one browser would work and another not.  Not  upgrade of the browser itself.  But instead some data stored in the browser not being compatible between Supabase code updates.  But I'm just throwing out ideas as a spectator.

**Comment by mallahyari** [comment]
I understand and thank you for the ideas. They might help anyway. I have dug Chrome even service workers, indexedDb, etc, just to realize what's going on and why it happens. But nothing.

**Comment by ibrahimkholil6210** [comment]
I've tried older version of supabase SDK where we call authentication method like `supabase.auth.signIn` this. This seems to work on chrome. But the latest version of the SDK doesn't work.

**Comment by kokecar11** [comment]
I am also having the same error with the twitch provider.

**Comment by okandavut** [comment]
I think our problems are same [#811](https://github.com/supabase/supabase-js/issues/811) and facing same problem. I tried downgrading the supabase-js version but not working.

**Comment by okandavut** [comment]
> It was working. But all of a sudden since last night it stopped. I haven't updated Chrome or Firefox last couple of days. I even tested on Safari and Edge and it doesn't work, the same blank page appears. Even in Firefox, you have open "dev tools" otherwise it doesn't work. That's weird and frustrating, because my whole app depends on it. I am looking to replace Supabase with another platform.

Totally the same issue. It works on firefox dev tools opened. Other browsers don't work.

**Comment by yeonjulee1005** [comment]
@okandavut  me too!! exactly same problem.. 
in firefox, activate normal.. but chrome not work signin...

i'm use `Nuxt 3.6.5`, `nuxtjs/supabase@0.3.8`

**Comment by quntherdev** [comment]
> > It was working. But all of a sudden since last night it stopped. I haven't updated Chrome or Firefox last couple of days. I even tested on Safari and Edge and it doesn't work, the same blank page appears. Even in Firefox, you have open "dev tools" otherwise it doesn't work. That's weird and frustrating, because my whole app depends on it. I am looking to replace Supabase with another platform.
> 
> Totally the same issue. It works on firefox dev tools opened. Other browsers don't work.

Same here, the loggin works only when dev tools opened (tried only on firefox).
When it's closed, I'm just redirected with the tokens in the url hash, but I'm not logged in.

**Comment by piscis** [comment]
I had the problem that `await supabase.auth.getSession()` after an client update suddenly never resolved which broke our login process. It seams the underlying issue is the go-true package. If you pin to 2.43.1 things start working again: 

```json
"pnpm": {
    "overrides": {
      "@supabase/gotrue-js": "2.43.1"
    }
  }
```

Found this here: https://github.com/nuxt-modules/supabase/issues/207

**Comment by j4w8n** [comment]
Thanks @piscis, there was a big change in 2.44.0. I can't test until next week, but hopefully someone else can.

**Comment by oliverrees** [comment]
I've got the same issue on next JS 13.4 - more detail [here](https://discord.com/channels/839993398554656828/1131729624649449614/1131729624649449614)

**Comment by okandavut** [comment]
> I had the problem that `await supabase.auth.getSession()` after an client update suddenly never resolved which broke our login process (all oAuth providers). It seams the underlying issue is the go-true package. If you pin to 2.43.1 things start working again:
> 
> ```json
> "pnpm": {
>     "overrides": {
>       "@supabase/gotrue-js": "2.43.1"
>     }
>   }
> ```
> 
> Found this here: [nuxt-modules/supabase#207](https://github.com/nuxt-modules/supabase/issues/207)

But I am not using Nuxt actually I am using React app + Vite and I can't manually downgrade go-truejs

**Comment by okandavut** [comment]
hey again,

I overrided the package of gotrue-js and it's worked!!!
```
"overrides": {
    "@supabase/supabase-js": {
      "@supabase/gotrue-js": "2.43.1"
    }
  }
```

<img width="414" alt="image" src="https://github.com/supabase/supabase/assets/10600157/f0567837-fdf6-429e-9231-025160417217">

**Comment by j4w8n** [comment]
> But I am not using Nuxt actually I am using React app + Vite and I can't manually downgrade go-truejs
> 

Setting an override in your package.json should still work to effectively "downgrade" the gotrue-js version. Afterwards, you'd need to `npm install` or equivalent.

**Comment by quntherdev** [comment]
> hey again,
> 
> I overrided the package of gotrue-js and it's worked!!!
> 
> ```
> "overrides": {
>     "@supabase/supabase-js": {
>       "@supabase/gotrue-js": "2.43.1"
>     }
>   }
> ```
> 
> <img alt="image" width="414" src="https://user-images.githubusercontent.com/10600157/255217585-f0567837-fdf6-429e-9231-025160417217.png">

It fixed the issue, thanks!
Don't forget to delete yarn-lock, package-lock, node-modules, and clean cache/cookies

**Comment by piscis** [comment]
After additional tests it turns out that mobile safari does not like gotrue-js version `2.43.1`, Safari does not support stack Guards and breaks the login. Also there is a new version of gotrue `2.45.0` which fixes the issue for stack guards in mobile safari, but the other issues still persist.

So to solve the issue of unsupported stack guards (`2.43.1`) and have a working login, we changed the overrides again to a combination of gotrue and supabase client which worked on our last release:

```json
"pnpm": {
    "overrides": {
      "@supabase/supabase-js": "2.24.0",
      "@supabase/gotrue-js": "2.38.0"
    }
  }
```

At least this seems to work for our mobile users as well as for the desktop clients.

**Comment by evelynf** [comment]
anyone else getting: "Application error: a client-side exception has occurred (see the browser console for more information)." when using these fixes? It will work for a bit and then I get this error

**Comment by yeonjulee1005** [comment]
@evelynf 
Me too, it's same getting error 
I have been contacting customer service to resolve this issue, but they also seem unwilling to resolve this issue.

<img width="782" alt="스크린샷 2023-07-23 오전 9 22 53" src="https://github.com/supabase/supabase/assets/57179957/c66312b8-a917-4cb1-81c8-f6ea449a818c">

**Comment by j4w8n** [comment]
@evelynf @yeonjulee1005 this is not the same issue as the original post. I'd recommend creating an issue on the gotrue-js repo and asking for clarification about what the warning means.

https://github.com/supabase/gotrue-js

**Comment by yeonjulee1005** [comment]
@j4w8n 
thank you! yes i understand 😄 
I had an issue (supabase auth not working) for an issue I'm following, 
and replaced gotrue-js with an older version to fix it.
I just only agreed with @evelynf mention about the problems that occurred during this replacement. 😃

**Comment by Prydeton** [comment]
For those using Yarn as their package manager, you will need to use "resolutions" rather than "overrides":

```json
"resolutions": {
  "@supabase/supabase-js": "2.24.0",
  "@supabase/gotrue-js": "2.38.0"
}
```

**Comment by hf** [comment]
Hey everyone, sorry you're having troubles with this. I believe this PR fixes the issues. I would kindly ask for your support in testing it and letting us know before we release it.

https://github.com/supabase/gotrue-js/pull/747

**Comment by j4w8n** [comment]
> Hey everyone, sorry you're having troubles with this. I believe this PR fixes the issues. I would kindly ask for your support in testing it and letting us know before we release it.
> 
> https://github.com/supabase/gotrue-js/pull/747

I'm not familiar with the process of testing a pr like that. Would you clone the branch and then merge it into local master?

**Comment by hf** [comment]
> I'm not familiar with the process of testing a pr like that. Would you pull the branch and then merge it into local master?

Hey so there are a couple of options:

- Check out the branch locally, `git clone` then `git checkout <branch-name>`
- Do `npm i` and `npm run build` to build it all
- Then you should use something like `npm link` or `yarn link`
- Within your project, do `npm link @supabase/gotrue-js`

Usually this is enough. But sometimes, `npm link` or equivalents don't work well. So what I end up doing most of the time is find all `node_modules/@supabase/gotrue-js` and remove them. Then in their place put in a symlink `ln -s` *with an absolute path* to the local copy of `gotrue-js`.

**Comment by j4w8n** [comment]
Ok, for some reason it was building the files as `Admin.js`, `Client.js`, etc inside `main` and `module`; instead of `GoTrueAdmin.js` and `GoTrueClient.js`. I went through and renamed files, then had to do the same for some references within the files. But after all of that, I can now login with the `implicit` flow.

**Comment by hf** [comment]
@J0 Mind explaining how you used `yalc` to test this?

**Comment by evelynf** [comment]
I tried the fix and it doesn't work on Safari but it does work on google chrome.

**Comment by lukeweston1234** [comment]
Unfortunately I am having this same problem, but only when registering a new user.

**Comment by izhan** [comment]
Having the same issue on multiple versions including latest, but occurring after token expires and needs to be refresh

**Comment by kangmingtay** [comment]
Hey everyone, i'm gonna close this issue since the main topic has been resolved already. If you guys are experiencing other issues with Supabase auth, I'd recommend creating a new issue to track it. This makes it alot easier for the team to get up to speed with the issue without wasting time to read the issue from the start only to find that the latest comments are referring to something else entirely. 

Thanks for the patience and feedback so far! If you think that the issue is a specific problem with your project and you can't find help on github, feel free to create a support ticket at https://app.supabase.com/support/new and we'd be more than happy to help yall out :)

**Comment by MickyLaitkor** [comment]
I tried all the solution like downgrade the @supabase/gotrue-js but still doesn't work. I am using Nextjs 13 and  instead of  session on cookies I got user and token on localStorage.
https://user-images.githubusercontent.com/132438556/258728921-b938d098-e3e2-4c8b-839f-aa6f92f9f947.png 
and I notice on network get user from from /auth/v1/user

**Comment by kangmingtay** [comment]
@MickyLaitkor can you please reach out to us at support - https://app.supabase.com/support/new ?

**Comment by vslio** [comment]
For the record this is still happening for me on my `expo` project and not just for `Google` sign in. I get the same for `Facebook` and `Email`. Only `Apple` sign in works fine.

For the record I'm using `"@supabase/supabase-js": "~2.33.1"`

The issues go away by adding the following to the `package.json` (bear in mind I'm using `yarn`):
```
"resolutions": {
  "@supabase/gotrue-js": "2.46.0"
}
```

However with that version of `gotrue-js` I'm getting the following warning on my project:
```
@supabase/gotrue-js: Stack guards not supported in this environment. Generally not an issue but may point to a very conservative transpilation environment (use ES2017 or above) that implements async/await with generators, or this is a JavaScript engine that does not support async/await stack traces. Safari is known to not support stack guards.
```

The warning above goes away by adding the following to the resolutions:
```
"resolutions": {
  "@supabase/gotrue-js": "2.42.0"
}
```

**Comment by 3IMAD69** [comment]
if anyone still having this issue with nextjs 13.5 you should add redirect option like this \

- jus
`const { data, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
            redirectTo: `${location.origin}/auth/callback`,
          },
      })`

**Comment by leouie28** [comment]
In my case only work on localhost development only, not working on deploymnet (vercel)

```
const { data, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
            redirectTo: `${location.origin}/auth/callback`,
          },
      })

```

**Comment by MickyRajkumar** [comment]
@rajan-personal what do you mean, by its work and redirected to supabase admin?

**Comment by rajan-personal** [comment]
I mean login is successful but it does not redirect to the application. Rather to admin supabase page.

**Comment by MickyRajkumar** [comment]
@rajan-personal It seems like there might be an issue with the login redirection URL probably you did not configure redirect url properly. To investigate this further, please provide the following information:
- The login code or configuration that specifies the redirection URL.
- The URL to which you are being redirected after a successful login
- If there are any error messages or logs related to the redirection issue.

**Comment by rajan-personal** [comment]
I am using latest release of supabase v0.23.06. 

I had it working for older version, but I am facing issue with newer version.

My login:

`await supabase.auth.signInWithOAuth(Provider.google);
            Future(() => {
              if (supabase.auth.currentSession != null) {
                context.go('/events')
              }
            });`

Callback url: https://api.mysave.app/auth/v1/callback
application url: https://web.mysave.app
I don't see any error. It logs in successfully and redirects to admin page, https://api.mysave.app.

**Comment by rajan-personal** [comment]
@MickyRajkumar Should I change callback url to frontend url?

**Comment by MickyRajkumar** [comment]
@rajan-personal you have to provide callback url like this

```const { data, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
            redirectTo: `${location.origin}/auth/v1/callback`,
          },
      })```

**Comment by rajan-personal** [comment]
@MickyRajkumar I am using dart and tried same. It is redirecting to supabase admin page directly after google.

User is redirected to google and he is not coming back to application. The callback is taking directly to supabase admin page.

**Comment by MickyRajkumar** [comment]
is this your supabase admin page https://api.mysave.app/? 
Additionally, remember to include your desired redirect URL within the Supabase URL configuration under 'Redirect URLs'.

**Comment by rajan-personal** [comment]
Yeah.. I tried.

**Comment by rajan-personal** [comment]
I want to know whats the most stable version for supabase.

**Comment by leikoilja** [comment]
> In my case only work on localhost development only, not working on deploymnet (vercel)
> 
> ```
> const { data, error } = await supabase.auth.signInWithOAuth({
>         provider: 'google',
>         options: {
>             redirectTo: `${location.origin}/auth/callback`,
>           },
>       })
> ```

Thanks, that got me thinking in the right direction. 
NextJS 13 , app directory with the latest versions of supabase and gotrue.

My issues was that authentication was going through just fine (locally using supabase docker sdk), but no session was set.
I needed to add
```js
  const handleAuthGoogle = async () => {
    SupabaseBrowserClient.auth.signInWithOAuth({
      provider: "google",
      options: {
        redirectTo: `${location.origin}/api/auth/callback`,  <---- points to my app's directory endpoint where i change code for session (from email authentication implementation )
      },
    });
  };

```

**Comment by volkerp** [comment]
I'm facing the same issue. vue SPA (no SSR). My app will get stuck exactly as described in the first post of this issue. Glad I found this report to learn it can be workaround by fixating the version of gotrue-js and supabase-js 
The versions that work for me are

```json
"dependencies": {
    "@supabase/supabase-js": "2.36.0",

},
"overrides": {
    "@supabase/gotrue-js": "2.44.0"
},
```

**Comment by GaryAustin1** [comment]
> I'm facing the same issue. vue SPA (no SSR). My app will get stuck exactly as described in the first post of this issue. Glad I found this report to learn it can be workaround by fixating the version of gotrue-js and supabase-js The versions that work for me are
> 
> ```json
> "dependencies": {
>     "@supabase/supabase-js": "2.36.0",
> 
> },
> "overrides": {
>     "@supabase/gotrue-js": "2.44.0"
> },
> ```

Can you be specific on what is like the first post.   Not clear from it what is meant by getSession does not return anything.

Do you make the getSession call and it never returns?

**Comment by volkerp** [comment]
I'm calling
```js
async function handleOAuthLoginGithub() {
  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'github',
    options: {
      redirectTo: 'http://localhost:8080/#/account',
    } })
  if (error) console.error('Error: ', error.message)

  console.log(data)
}
```

the redirection process kicks off, redirection to gihub, than back again to the redirectUrl in my vue app.

When it is not working (i.e. with recent supabase-js/gotrue-js version) the redirectUrl is called with added _#access_token=eyJhbGci…&refresh_token=psVOeU…DNT2o2VA&token_type=bearer_ and get stuck at this point. i.e. the url is not cleaned up, the `supabase.auth.onAuthStateChange()` callback reports INITAL_SESSION null,  successive calls to ```supabase.auth.getSession()``` return undefined.

Fixating the version as I described makes the problem go away (with no changes to the code, supabase configuration, auth provider configuration etc) In this case again a 302 redirect happens to the redirectUrl with added tokens in the same manner but now the url get processed and parameters are removed. `supabase.auth.onAuthStateChange()` callback reports SIGNED_IN and a valid session object, so do subsequent calls to getSession()

**Comment by GaryAustin1** [comment]
@volkerp  Thanks.  That is not in line with the other issue I was worried you might be encountering based on getSession actually returning.  It was not clear if it was returning null or not returning based on the OPs original post.  There is an issue that locks up the next request IF you do a supabase call in the onAuthStateChange handler.  
Got no help on what you are seeing.

**Comment by jerocosio** [comment]
I'm not sure if this can help some but I was stuck with this issue (`Failed to fetch RSC payload for Falling back to browser navigation`) for almost a full day, and I figured out that my error was that I was adding a re-direction after calling signInWithOAuth, like so:

```
const { data, error } = await supabase.auth.signInWithOAuth({
        provider: provider,
        options: {
          redirectTo: `${getURL()}auth/callback`
        }
      });
      if (!error) {
        **router.push(vieneDe || '/panel');**
      }
```

For some reason it worked well on Chrome, but it failed on Safari / Webkit.

**Comment by alxvallejo** [comment]
Everyone's talking about redirectTo `${getURL()}auth/callback`. Well what the hell is in that route? Shouldn't there be a provider wrapper that listens for the auth state change and handles storing the user/session automatically so you can just route to any protected route and the session will be there?

**Comment by YO-SC** [comment]
Hello, I am having similar issues as this closed issue.

I have an NextJS 14 app with email + password login, and I wanted to add Oauth into the mix. I am running all the login logic on [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations). Currently on a `localhost` environment, the app is not hosted at the moment. 

The server action being used:
```
'use server'

import { createClient } from '@/utils/supabase/server'
import { cookies } from 'next/headers'

export async function loginWithGoogle() {
  const cookieStore = cookies()
  const supabase = createClient(cookieStore)
  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: 'http://localhost:3000/',
      queryParams: {
        access_type: 'offline',
        prompt: 'consent',
      },
    },
  })

  if (error) {
    console.error(error.message)
    return error.message
  }

  redirect(data.url) // to google's auth page
}
```

Here are my dependencies:
```
    "@supabase/ssr": "^0.1.0",
    "@supabase/supabase-js": "^2.39.3",
    "next": "14.1.0",
    "react": "^18",
    "react-dom": "^18",
```

When I get redirected back to my app, both `session` and `user` are still `null`. Using the `getUser()` and `getSession()` functions on my SSR front-end.

I ask, do I need `@supabase/gotrue-js`? Doesn't `@supabase/ssr | supabase-js` have the same functionality? Thx y'all


For more context, I followed the [official Supabase instructions](https://supabase.com/docs/guides/auth/social-login/auth-google)

**Comment by charislam** [comment]
No, you shouldn't need to separately install `@supabase/gotrue-js`, it's already a dependency of `@supabase/ssr`.

Have you tried the instructions that are specific to [Server-Side Auth](https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr)? With `@supabase/ssr`, you are automatically opted into the PKCE flow, so you'll need to handle the code exchange.

**Comment by YO-SC** [comment]
> No, you shouldn't need to separately install `@supabase/gotrue-js`, it's already a dependency of `@supabase/ssr`.
> 
> Have you tried the instructions that are specific to [Server-Side Auth](https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr)? With `@supabase/ssr`, you are automatically opted into the PKCE flow, so you'll need to handle the code exchange.

hello, I didn't noticed those instructions. Thx. 👍🏼 . I will read them and take the appropriate steps.

**Comment by libkakashi** [comment]
I'm having the same issue with google and twitter signin. No error logs, no issues in the authentication flow, but nothing happens after redirect. The session object is always empty. 

Also, interestingly, it only happens on vercel. I deployed the same commit and same .env on digitalocean and it works just fine. Probably something to do with serverless in my case. Still figuring it out

**Comment by Nelhoa** [comment]
> I'm having the same issue with google and twitter signin. No error logs, no issues in the authentication flow, but nothing happens after redirect. The session object is always empty.
> 
> Also, interestingly, it only happens on vercel. I deployed the same commit and same .env on digitalocean and it works just fine. Probably something to do with serverless in my case. Still figuring it out

I’m facing the same issue as you but with cloudflare. In my local env it works perfectly fine (linked to my remote db). Have you found any solution yet ?

**Comment by burhanusman** [comment]
Had similar issue. Fixed it by changing` redirectTo: ${origin}/auth/callback` to  `redirectTo: ${process.env.NEXT_PUBLIC_BASE_URL}/auth/callback` . For some reason ${origin} was not working on Vercel

**Comment by jt6677** [comment]
This bug is so unbelievable .  `    const { data: authListener } = supabaseClient.auth.onAuthStateChange((event, session) => {
           console.log('first', event, session)
      // if (event === 'SIGNED_IN' && session) {
      //   setUser(session.user)

      //   setSession(session)
      // }
    })

    return () => authListener.subscription.unsubscribe()
  }, [])`                  Event after redirect from google is never changed to SIGNED_IN and session is just null.

**Comment by jt6677** [comment]
I came from   "@supabase/supabase-js": "2.39.8",     this should not be closed.

**Comment by Razikus** [comment]
its still an issue

**Comment by kafle1** [comment]
same here

**Comment by jt6677** [comment]
This strange bug made me refactor my entire app to Nextjs. It seems supabase only focuses on implementation in Nextjs. Everything in theory should work in regular React but in reality, it just does not work. After switching to Nextjs, I never experienced this problem again.   supabaseClient.auth.onAuthStateChange((event, session) => { console.log('first', event, session) return () => authListener.subscription.unsubscribe() }, [] The event is always properly set as "SIGNED_IN".  This WAS NOT the case in my old React app. I have not changed any setting in GoogleSignIn. 

At some point, you just have to bite the bullet and go with Supabase's decision. (NextJs).

**Comment by Razikus** [comment]
This bug is because supabase supports mainly hash router
Not history router

**Comment by milanpoliak** [comment]
The latest version still only works in Firefox. On Chrome it gets stuck and never fires the `SIGNED_IN` event.

**Comment by ElectricCodeGuy** [comment]
I think i actually found the bug after some hours digging though it...
So my Domains is connected to Vercel where i both have [lovguiden.ai](https://lovguiden.ai/) and also [www.lovguiden.ai](https://www.lovguiden.ai/)
I have set it up as recommended by Vercel to redirect to [www.lovguiden.ai](https://www.lovguiden.ai/)
In supabase at the Redirect URLs i just had https://lovguiden.ai/api/auth/callback 
So when I tried to use Social Auth with Google it would correctly create the account in Supabase Auth using SSR, but it would always redirect me to the root page withe code attached to the URL. 

The reason is that when Supabase Auth redirects to https://lovguiden.ai/api/auth/callback, since I specified this, Vercel domain control then in return redirects me to https://www.lovguiden.ai/ but without the "api/auth/callback" so I would always end up on  the root page...

I changed my Redirect urls on supabase to https://www.lovguiden.ai/ and now it works as expected using:

```
import { createClient } from '@/lib/client/client';

export async function signInWithGoogle() {
  const supabase = createClient();

  await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: `${location.origin}api/auth/confirm`
    }
  });
}
```

This was awful to figure out..............

**Comment by jdtzmn** [comment]
I was facing similar issues. In case anyone else has this issue, double-check that when you're trying to use the PKCE flow you create a Supabase client with `@supabase/ssr`. I was creating the client with `supabase/supbase-js` which meant when I called `signInWithOAuth()` it returned with an `access_token` hash instead of the raw code.

**Comment by tomery11** [comment]
> I was facing similar issues. In case anyone else has this issue, double-check that when you're trying to use the PKCE flow you create a Supabase client with `@supabase/ssr`. I was creating the client with `supabase/supbase-js` which meant when I called `signInWithOAuth()` it returned with an `access_token` as a URL hash instead of a query with the raw code.

did you use react? or next?

**Comment by QuocThuanTruong** [comment]
Still got this issue, it's so annoying

**Comment by CropWatchDevelopment** [comment]
This is scary as it is nice to know security is done correctly, but with Supabase security always feels half baked.
Is there any examples of this with Sveltekit? I can get it working, but this all feels very hand wavy to me.

**Comment by j4w8n** [comment]
> This is scary as it is nice to know security is done correctly, but with Supabase security always feels half baked.
> Is there any examples of this with Sveltekit? I can get it working, but this all feels very hand wavy to me.

If you're doing server side auth, then my demo app has oauth login, within actions: https://github.com/j4w8n/sveltekit-supabase-ssr

**Comment by alley-oop-sales-platform** [comment]
same problem here

`redirect_uri = url_for('auth_callback', _external=True)
    
    res = supabase.auth.sign_in_with_oauth({
        "provider": "google",
        "options": {
            "redirect_to": redirect_uri,
            "scopes": "email profile",
            "queryParams": {
                "state": state,
                "access_type": "offline",
                "prompt": "consent"
            }
        }
    })`

`@app.route('/auth/callback')
def auth_callback():
    logger.info('Serving /auth/callback page')
    logger.info(f"Session at start of callback: {json.dumps(dict(session))}")
    logger.info(f"Full request URL: {request.url}")
    logger.info(f"Request args: {request.args}")
    
    try:
        # Parse the query string from the full URL
        parsed_url = urlparse(request.url)
        query_params = parse_qs(parsed_url.query)
        logger.info(f"Parsed query parameters: {query_params}")

        # Check if there's an error
        if 'error' in query_params:
            raise Exception(f"OAuth error: {query_params['error'][0]}")

        # Verify state
        received_state = query_params.get('state', [None])[0]
        expected_state = session.get('oauth_state')
        logger.info(f"Received state: {received_state}")
        logger.info(f"Expected state: {expected_state}")`

`ERROR - Error in auth callback: Invalid state parameter. Received: None, Expected: HIa9pSW_lK-RZ6SVRbIUcA`

**Comment by sbhatm1213** [comment]
Facing this error still `AuthSessionMissingError: Auth session missing!` at http://localhost:3000/static/js/bundle.js:79331:20

Steps followed -
Add Client ID and Secret on Supabase Google Auth Provider - Done
Add Javascript origin - Done - http://localhost:3000/
Add Redirect URI - Done - http://localhost:3000/auth/v1/callback and https://my-domain.supabase.co/auth/v1/callback

Same issue even with Azure

Although login happens, cannot get the session/user

**Comment by The-LukeZ** [comment]
For the rest who still face this issue, I made a longer Explanation here: https://github.com/orgs/supabase/discussions/35788
