### ISSUE TITLE
MFA example is missing RLS policy for mfa_factors

### ISSUE THREAD

**Issue by KirioXX** [supabase/supabase#17168]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/auth-mfa

## Describe the problem

I tried to implement MFA and enforce only for users that have opted-in.
But when I try to fetch now I get this error:
```sh
permission denied for table mfa_factors
```
I tried a couple combinations to make mfa_factors readable but I can't get it to work.

## Describe the improvement

It would be great to have also an example RLS policy for the mfa_factors 
to make them accessible only for the MFA check.

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by itsajay1029** [comment]
I'd like to work on this if you guide me a little @KirioXX

**Comment by itsajay1029** [comment]
Is this something I can refer and add to the docs : [MFA AUTH VIA RLS]( https://supabase.com/blog/mfa-auth-via-rls#enforcement-via-row-level-security 
)

**Comment by KirioXX** [comment]
Hey @itsajay1029,

Thanks for responding! The docs actually already have some examples for RLS policies here:
https://supabase.com/docs/guides/auth/auth-mfa#enforce-rules-for-mfa-logins

I think those are the same as the one in the article. But they miss a policy for the auth.mfa_factors table.
Without that the other policies are useless and will fail.

**Comment by Collin0810** [comment]
Hi @KirioXX,

I encountered a similar issue and managed to resolve it by creating a separate `check_mfa` function set as a `SECURITY DEFINER`.

This function enforces MFA when the user has at least one MFA factor verified:
```
CREATE OR REPLACE FUNCTION public.check_mfa()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN (
        array[auth.jwt()->>'aal'] <@ (
            SELECT
                CASE
                    WHEN count(id) > 0 THEN array['aal2']
                    ELSE array['aal1', 'aal2']
                END
            FROM auth.mfa_factors
            WHERE auth.uid() = user_id AND status = 'verified'
        )
    );
END;
$$;
```

Once created, you can implement the checks in your RLS policies as follows:
```
check_mfa() AND auth.uid() = user_id
```

Hope this helps!

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!

**Comment by drefrajo** [comment]
Hi @kiwicopple!

I just wanted to let you know that this issue still exists.
The code in your [documentation](https://supabase.com/docs/guides/auth/auth-mfa#enforce-rules-for-mfa-logins):

```sql
create policy "Policy name."
  on table_name
  as restrictive -- very important!
  to authenticated
  using (
    array[auth.jwt()->>'aal'] <@ (
      select
          case
            when count(id) > 0 then array['aal2']
            else array['aal1', 'aal2']
          end as aal
        from auth.mfa_factors
        where auth.uid() = user_id and status = 'verified'
    ));
```

still returns an error `permission denied for table mfa_factors`.

The solution proposed by @Collin0810 works as expected, but it would be really nice if this was mentioned somewhere in the documentation. 

Thanks!

**Comment by Hallidayo** [comment]
Hi all, I've just been testing and it seems that the query is no longer erroring. I'm going to close this one but please feel free to reach out if still an issue.

**Comment by carl0shd** [comment]
@Hallidayo i have the same error with latest Supabase changes at 18 august. i am using the example RLS about to enforce rules only for users that have opted-in.

<img width="460" alt="Screenshot 2024-08-18 at 2 04 52 AM" src="https://github.com/user-attachments/assets/8b0a66dd-feb2-46a9-b46b-5ce237876794">

**Comment by laurencebedford** [comment]
Not too sure if its the same issue with myself as I dont receive the message "permission denied for table mfa_factors" however when I use the following policy:

```
create policy "Policy name."
  on table_name
  as restrictive -- very important!
  to authenticated
  using (
    array[(select auth.jwt()->>'aal')] <@ (
      select
          case
            when count(id) > 0 then array['aal2']
            else array['aal1', 'aal2']
          end as aal
        from auth.mfa_factors
        where ((select auth.uid()) = user_id) and status = 'verified'
    ));


```

Stated in the docs:
https://supabase.com/docs/guides/auth/auth-mfa#enforce-rules-for-mfa-logins


And then use the supabase dashboard RLS impersonator with AAL2 I still cannot read the table.

![image](https://github.com/user-attachments/assets/7d63a8e6-1128-43a0-9a4d-b63d8579a702)

**Comment by Hallidayo** [comment]
Hi all, sorry only just seen these comments. I'll re-open the issue now and we can investigate.

**Comment by J0** [comment]
Hey team,

Thanks @Hallidayo for jumping on this and @laurencebedford for flagging. Can I confirm that the user  impersonated has a verified factor in `auth.mfa_factors`? 

The policy below:

```
create policy "Policy name."
  on table_name
  as restrictive -- very important!
  to authenticated
  using (
    array[(select auth.jwt()->>'aal')] <@ (
      select
          case
            when count(id) > 0 then array['aal2']
            else array['aal1', 'aal2']
          end as aal
        from auth.mfa_factors
        where ((select auth.uid()) = user_id) and status = 'verified'
    ));

```

requires that the user have a verified factor alongside being AAL2.

At time of writing you can insert a factor like:

```
INSERT INTO
  auth.mfa_factors (id,user_id, factor_type, status, created_at, updated_at)
VALUES
  ('<fake-user-id-like-0376b32c-5167-40b0-bbc4-a37322a25434>', '<user_id>', 'totp', 'verified', now(), now());
```
or by going through the MFA process.

Let us know!
Joel

**Comment by laurencebedford** [comment]
This was a while back, however I believe so. I was using the impersonation via the supabase dashboard. To get around this ive been using from @Collin0810

**Comment by J0** [comment]
Could we trouble you to try again and check if possible? We've tried a couple of combinations but are unable to reproduce the issue.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by Dramelac** [comment]
This policy `Enforce only for users that have opted-in` on the official docuementation still produce the mentionned above error 
```
code	"42501"
details	null
hint	null
message	"permission denied for table mfa_factors"
``` 
Policy from https://supabase.com/docs/guides/auth/auth-mfa#database

There is no activity because there is much to add to the subject, can you please update the documentation with a working policy ?

Thank you very much for re-opening the issue and updating the official documentation !

**Comment by Dramelac** [comment]
PoC from supabase table editor while impersonating a user:

![Image](https://github.com/user-attachments/assets/8dd7ce7a-b151-49c1-b36b-711125846d33)
