### ISSUE TITLE
Cannot start supabase-vector container, hence cannot start supabase locally

### ISSUE THREAD

**Issue by ibito** [supabase/supabase#17412]
**Describe the bug**
Trying to start the dockerized version of supabase locally gives me an error, when doing `docker compose up -d` it shows this:
![image](https://github.com/supabase/cli/assets/180943/eedfcb12-aa2e-4cc5-8891-f396abbae222)

**To Reproduce**
1. Following the [Supabase guide on self hosting](https://supabase.com/docs/docs/guides/self-hosting/docker#running-supabase) until the step where you start the containers: `docker compose up -d` it will show the above screenshot 
2. Using `docker logs e9fc6a1bb4c2` (which is the id of my supabase-vector container) will show the following:
![image](https://github.com/supabase/cli/assets/180943/a312b708-1cf7-4baa-aaf6-e542c617656e)

**Expected behavior**
All containers should show "started" correctly

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (WSL)

**Comment by soedirgo** [comment]
Can you check if [this change](https://github.com/supabase/supabase/pull/17344) fixes it for you?

**Comment by nicetomytyuk** [comment]
Hi @ibito , you can try the solution from [this issue](https://github.com/supabase/supabase/issues/17343#issuecomment-1715944131), I've managed to resolve it by changing the:

`.metadata.parsed.error_severity = upcase(.metadata.parsed.error_severity)`

to

`.metadata.parsed.error_severity = upcase!(.metadata.parsed.error_severity)`

**Comment by raajnadar** [comment]
Come on guys, I was trying to use supabase for the first time and I got this issue

My first time experience was so poor 😔

**Comment by SoCodeNow** [comment]
> Come on guys, I was trying to use supabase for the first time and I got this issue
> 
> My first time experience was so poor 😔

Me too, very poor experience indeed~

**Comment by ibito** [comment]
Yes! this fixes it! Thank you everyone!

**Comment by SoCodeNow** [comment]
@ibito  How did you fix it? I tried:
'.metadata.parsed.error_severity = upcase!(.metadata.parsed.error_severity)'
Can not start Container supabase-vector
`.metadata.parsed.error_severity = upcase!(.metadata.parsed.error_severity)`
and
`.metadata.parsed.error_severity, err = upcase(.metadata.parsed.error_severity)`
Shows: dependency failed to start: container supabase-analytics is unhealthy

**Comment by kafiarifin** [comment]
> Hi @ibito , you can try the solution from [this issue](https://github.com/supabase/supabase/issues/17343#issuecomment-1715944131), I've managed to resolve it by changing the:
> 
> `.metadata.parsed.error_severity = upcase(.metadata.parsed.error_severity)`
> 
> to
> 
> `.metadata.parsed.error_severity = upcase!(.metadata.parsed.error_severity)`

My issue solved with this solution, thans dude @nicetomytyuk !

**Comment by ibito** [comment]
> @ibito How did you fix it? I tried: '.metadata.parsed.error_severity = upcase!(.metadata.parsed.error_severity)' Can not start Container supabase-vector `.metadata.parsed.error_severity = upcase!(.metadata.parsed.error_severity)` and `.metadata.parsed.error_severity, err = upcase(.metadata.parsed.error_severity)` Shows: dependency failed to start: container supabase-analytics is unhealthy
> 
> Tried both on ubuntu and centos.

Sorry, I'm not experienced in this language? I just tried what was in [this reply](https://github.com/supabase/supabase/issues/17412#issuecomment-1718943131) and it worked

**Comment by jonathanstiansen** [comment]
I'm still getting this. I don't think this should be closed.

**Comment by vicXvac** [comment]
i was having trouble with the vector container as well which was causing all the containers to be stopped otherwise switching off analytics was the way it was working, i was using docker desktop at the time but when i switched to the default docker context from the host maching and not using the context for the docker desktop it started working fine with no issues, am using parrot os with gnome DE

**Comment by soedirgo** [comment]
Can you create a separate issue? It most likely has a different root cause.
