### ISSUE TITLE
error at docker-compose up -d Container is unhealthy

### ISSUE THREAD

**Issue by markbara-git** [supabase/supabase#17421]
# Bug report

- [*] I confirm this is a bug with Supabase, not with my own application. 
- [*] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When following the guide at: https://supabase.com/docs/docs/guides/self-hosting/docker
when running the command "docker-compose up -d" the output reads: "ERROR: for db  Container "5880505a98ed" is unhealthy.
ERROR: Encountered errors while bringing up the project.".
I did copied the .env.example into .env and run 'docker-compose pull'.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to  'https://supabase.com/docs/guides/self-hosting/docker' and fallow the first steps
2. Get the code 'git clone --depth 1 https://github.com/supabase/supabase'
3. Go to the docker folder 'cd supabase/docker'
4. Copy the fake env vars 'cp .env.example .env'
5. Pull the latest images 'docker compose pull'
6. Start the services (in detached mode) 'docker compose up -d'
7. See error

![268253568-eb7888c8-80f3-4107-85dd-3ad4b5f91f24](https://github.com/supabase/supabase/assets/83405406/d6118c86-8776-4638-9f1c-2d480ecb9fce)

## Expected behavior

I was expecting composing of the docker image.

## System information

- OS: Debian 12 amd64
- Version of supabase-js: current from the day of this post
- Version of Node.js: current from the day of this post

**Comment by nicetomytyuk** [comment]
Try the solution from [this issue](https://github.com/supabase/supabase/issues/17412#issuecomment-1718943131). Else try to add more logs from the docker, you can run it without -d to see all the logs.

**Comment by tkintenn** [comment]
same issue. ubuntu 22.04 lts. Docker logs show: 

```
error[E103]: unhandled fallible assignment
   ┌─ :15:35
   │
15 │ .metadata.parsed.error_severity = upcase(.metadata.parsed.error_severity)
   │ --------------------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │ │                                 │
   │ │                                 this expression is fallible
   │ │                                 update the expression to be infallible
   │ or change this to an infallible assignment:
   │ .metadata.parsed.error_severity, err = upcase(.metadata.parsed.error_severity)
   │

```
This was a change committed 3 weeks ago.

**Comment by SoCodeNow** [comment]
Same issue, can not instal and start supabase both on Ubuntu 22 and Centos. And tried all the work around:
https://github.com/supabase/supabase/issues/17412#issuecomment-1720370433

**Comment by markbara-git** [comment]
> Try the solution from [this issue](https://github.com/supabase/supabase/issues/17412#issuecomment-1718943131). Else try to add more logs from the docker, you can run it without -d to see all the logs.

Unfortunately your answer does not apply to my issue, and also running the docker-compose up without -d option does not show anything more then running it with the -d option.
![Screenshot 2023-09-15 122017](https://github.com/supabase/supabase/assets/83405406/5711eaa4-2915-4e24-983b-174130b56a45)

**Comment by Ziinc** [comment]
This bug has been fixed https://github.com/supabase/supabase/pull/17344#pullrequestreview-1630590778

**Comment by Ziinc** [comment]
@markbara-git please try pulling the latest changes and run the following:
```bash
# pull latest changes
git pull origin master

# clear all existing containers
docker compose down

# restart with logs output to stdout
docker compose up 
```

**Comment by markbara-git** [comment]
@Ziinc pulling lates changes didn't solve the issue:

![Screenshot 2023-09-18 135043](https://github.com/supabase/supabase/assets/83405406/6aa2d93a-4232-4a76-8f02-c08b6b0f4d5f)

**Comment by markbara-git** [comment]
Tried this again today on fresh OS and with latest repo. Same errors accrue:
![Zrzut ekranu 2023-10-10 092202](https://github.com/supabase/supabase/assets/83405406/23abe67f-601f-480f-b5b5-3d75e6bac7ae)
