### ISSUE TITLE
Next.js App Router, createServerComponentClient fails when using 'next dev --turbo'

### ISSUE THREAD

**Issue by baufometic** [supabase/supabase#17586]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Occurs when using pnpm.
Occurs when using the Next.js App Router.
Occurs in Server Components that use `createServerComponentClient`.
Runs fine when using `npm run dev` as usual, without Turbo.
Repro URL below.

The following gets console logged in the VSCode terminal:

```
ModuleBuildError: error - node_modules/.pnpm/node-gyp-build@4.6.1/node_modules/node-gyp-build/node-gyp-build.js:22:10  Error resolving commonjs request

  20 | 
  21 | function load (dir) {
> 22 |   return runtimeRequire(load.resolve(dir))
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 23 | }
     | ^
  24 | 
  25 | load.resolve = load.path = function (dir) {
  26 |   dir = path.resolve(dir || '.')
unable to resolve dynamic
It was not possible to find the requested file.
    Parsed request as written in source code: dynamic
    Path where resolving has started: [project]/node_modules/.pnpm/node-gyp-build@4.6.1/node_modules/node-gyp-build/node-gyp-build.js
    Type of request: commonjs request
    Import map: No import map entry
```

## To Reproduce

- [Clone this repo](https://github.com/baufometic/supabase-turbo-issue)
- Visit `/user/dashboard`

## System information

- Ubuntu 22.04
- VSCode 1.82.2
- PNPM 8.7.6
- Chrome / Chromium / Firefox
- @supabase/auth-helpers-nextjs: 0.8.1,
- @supabase/supabase-js 2.34.0

- Version of Node.js: 18.18.0

## Additional context
Doesn't occur when running regular `npm run dev`

**Comment by baufometic** [comment]
Mods, apologies but not sure how to cross post - or reference the issue in [Vercel/Turbo](https://github.com/vercel/turbo) and [Vercel/Next](https://github.com/vercel/next.js)

**Comment by gnaneshwar718** [comment]
i would to work on it

**Comment by gnaneshwar718** [comment]
i would like to work on it

**Comment by paulphys** [comment]
running into the same issue on next@13.5.5-canary.3

**Comment by joshcawthorne** [comment]
Echoing this issue, on next@14.0.0 and supabase-js@2.38.4.

**Comment by jmarks-joshua** [comment]
I don't believe this is a supabase issue, I'm going through the new https://nextjs.org/learn tutorial which doesn't include supabase at all, and I get this error on an async server component when anywhere in the import chain includes importing from '@vercel/postgres'

**Comment by thexpand** [comment]
@jmarks-joshua Yes, I'm going through the https://nextjs.org/learn tutorial as well and all of a sudden this happens. I can't recall what triggered it, so I can't really pin-point the reason why it's happening. I tried deleting `node_modules` and then running `npm install` once again, but it's still not working. I also tried deleting the `.next` directory and running the dev server again, but to no avail. I believe it's a Next.js bug, not a Supabase one.

**Comment by abiddraws** [comment]
```
import { createBrowserClient } from "@supabase/ssr";

export const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  );
```
When using the `--turbo` option, the issue arises only when creating a Supabase client. The error occurs whether you use `createBrowserClient` or `createServerClient`. Without making a Supabase client call, the code works as expected.

**Comment by o-az** [comment]
same issue only when using turbo.

**Comment by encima** [comment]
Is this issue still occurring for people on the latest version of this repo? From this (and linked issues), it seems like a `next` issue rather than a Supabase one but I am happy to keep open if it is impacting development.

**Comment by abiddraws** [comment]
@encima This issue is resolved in latest version
`
"@supabase/ssr": "^0.0.10",
"@supabase/supabase-js": "latest",
"next": "14.1.1-canary.5",
`

**Comment by gokulkrishh** [comment]
@abiddraws it seems issue is still there in "next": "^14.1.1-canary.27", and `@supabase/ssr": "^0.1.0`.
