### ISSUE TITLE
Drawer Footer not visible on iPadOS

### ISSUE THREAD

**Issue by TimKolberger** [supabase/supabase#18317]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The drawer footer with Submit and Close Buttons is not visible on iPadOS 17.0.2.
This issue is consistent across different drawers like new table, new function etc.

This prevents creating new tables etc on an iPad.

Guessing that the drawer body has a defined height, which is incompatible with iOS.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/dashboard/project/ID/editor
2. Click on New Table
3. Try to locate the Buttons

## Expected behavior

If the drawer content overflows the screen I want to be able to scroll down to interact with the buttons.

## Screenshots

With no tabs open:
![image](https://github.com/supabase/supabase/assets/16899513/11808f84-ab76-4a89-9554-708f8f558306)

With additional tabs open:
![image](https://github.com/supabase/supabase/assets/16899513/73e0307a-3330-4bb0-823f-41c0c27ada3c)

## System information

- OS: iPad 17.0.2
- Browser: safari 

## Additional context

—

**Comment by jonshung** [comment]
Correct me if I'm wrong, I'm pretty new here.
This seems to be a bug on mobile device browsers, especially safari. Setting the view height of the panel to 100% might fix the problem but since the base style for the it was previously set to "screen", which by iOS's (and maybe others) default behavior, use a larger viewport unit then what is rendered, thus overriding the 100% rule.
Proposed fix is to set the base style's height value based on the dvh unit, though some older browsers might not support it, so it is better to have a "height: 100vh" fallback.

**Comment by Ayushhgupta39** [comment]
@TimKolberger As of now, I'm seeing the project and trying to produce your issue, it looks to me that buttons are fixed on their position and causing no issue while creating the table. Is there something I'm missing out on this? I want to contribute to this and fix this issue.

**Comment by TimKolberger** [comment]
I can still reproduce it as described. Seems an issue with mobile safari. Maybe 100dvh for the Drawer height could fix this.

**Comment by Ayushhgupta39** [comment]
Okay, I see it now, and I checked it on and Android device also, and it's the same issue, so I guess this is an issue with the mobile devices over all not just with IOS
![image](https://github.com/supabase/supabase/assets/96309609/ca676d95-bd46-48b8-86e1-61b70c5d932c)

**Comment by Bayyana-kiran** [comment]
can i work on this issue?

**Comment by Ayushhgupta39** [comment]
@Bayyana-kiran I think you can go ahead and raise a PR instead and mention the issue in it.

**Comment by Bayyana-kiran** [comment]
@Ayushhgupta39 is this issue already sorted?

**Comment by Ayushhgupta39** [comment]
No I don't think it is resolved yet

**Comment by mevans** [comment]
Currently seeing the same described issue on iPad pro 11inch
