### ISSUE TITLE
Set-Cookie header is ignored

### ISSUE THREAD

**Issue by harel-tussi** [supabase/supabase#18564]
# Bug report

## Describe the bug

Set-Cookie header is ignored in response from url: http://localhost:3000/auth/sign-in. The combined size of the name and value must be less than or equal to 4096 characters.

## To Reproduce

Use the new supabase/ssr package

```
import { createServerClient, type CookieOptions } from "@supabase/ssr";
import { cookies } from "next/headers";

export const createClient = (cookieStore: ReturnType<typeof cookies>) => {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options });
          } catch (error) {
            // The `set` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.delete({ name, ...options });
          } catch (error) {
            // The `delete` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    }
  );
};

```

## Expected behavior

Should be able to set the cookie

**Comment by spaghetti-coder-yyz** [comment]
Having this issue as well - I'm not sure what happened, it was working and then stopped. Isolated tests also have this error:

![CleanShot 2023-11-02 at 12 04 02@2x](https://github.com/supabase/supabase/assets/21662569/af229139-22f6-462b-8886-1c61c8288a90)

**Comment by ShlomiKo** [comment]
Having the same issue with Facebook login, Google login works great but facebook loogin fails and the cookie error is showing in the console

**Comment by orenaksakal** [comment]
afaik this is fixed here https://github.com/supabase/auth-helpers/pull/669/files

**Comment by dvvolynkin** [comment]
Updated to 0.0.7
Still have this problem

**Comment by dijonmusters** [comment]
Could you try updating to 0.0.9? If this is still not working could you [DM me](https://twitter.com/jonmeyers_io) a link to a GitHub repo so I can take a look?

**Comment by arinaldi** [comment]
Updating to 0.0.9 fixed the issue for me. Thanks @dijonmusters

**Comment by dvvolynkin** [comment]
@dijonmusters 
```
export const createSupabaseRouteHandlerClient = (anon: boolean = true): SupabaseClient<Database> => {
  const cookieStore = cookies()

  return sbSSR.createServerClient<Database>(
    env.NEXT_PUBLIC_SUPABASE_URL!,
    anon ? env.NEXT_PUBLIC_SUPABASE_ANON_KEY! : env.SUPABASE_SERVICE_ROLE_KEY!,
    {
      cookieOptions: getCookieOptions(),
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
        set(name: string, value: string, options: sbSSR.CookieOptions) {
          console.log("cookie length", value.length)
          cookieStore.set({ name, value, ...options })
        },
        remove(name: string, options: sbSSR.CookieOptions) {
          cookieStore.set({ name, value: '', ...options })
        },
      },
    }
  )
}
```
cookie length in chunk is 3143

But after encoding in Set-Cookie header value length is 4262

**Comment by nikitastryuk** [comment]
Facing this as well

 "supabase": "^1.115.0"

**Comment by tyforcode** [comment]
This is still happening for me `"@supabase/ssr": "^0.0.10"` , `"@supabase/supabase-js": "^2.39.1"`. Seems related to additional metadata attached to the user object. 

The session returns properly but the cookie cannot be set...

**Comment by spaghetti-coder-yyz** [comment]
Yes same here - if I login with a user with no metadata, the cookie is fine and no issue. I've had to refactor my app to store the metadata previously in the user into a separate table: userdata

**Comment by Aietes** [comment]
I'm facing this issue as well. I'm not sure why this issue is closed, as the issue persists with the latest version. Is there any feasible workaround available?

**Comment by 0xmax** [comment]
yeah, why is this closed? happening to me too, any workaround known?

**Comment by Aietes** [comment]
It seem this is fixed with the lates supabase-ssr 0.1.0 release. 👍🏻

**Comment by layerzzzio** [comment]
I still have the same issue with supabase-ssr 0.1.0 and supabase-js 2.39.7.

**Comment by HunterWhiteDev** [comment]
@layerzzzio Did you ever fix this?

**Comment by encima** [comment]
Can you confirm you are running the latest releases of both packages. If you are experiencing the issue, please also provide the length of the cookie to help us investigate.

**Comment by MirroxDev** [comment]
I use `"@supabase/ssr": "\^0.0.10", "@supabase/supabase-js": "\^2.42.0",` ,and I have the same error .

I checked the length of my cookies , the length of my cookies `cookie length 3180,cookie length 755`
and this is less than 4096.
`cookies: {
          get(name: string) {
            return cookieStore.get(name)?.value;
          },
          set(name: string, value: string, options: CookieOptions) {
            console.log("cookie length", value.length)
            cookieStore.set({ name, value, ...options });
          },
          remove(name: string, options: CookieOptions) {
            cookieStore.delete({ name, ...options });
          },
        },`
