### ISSUE TITLE
Going from "@types/node": "^18.16.13" -> "@types/node": "^18.18.8", causes typechecking to fail.

### ISSUE THREAD

**Issue by derekdowling** [supabase/supabase#18740]
# Bug report

For:
```
"typescript": "^5.0.4",
"supabase": "^1.110.1",
"@types/node": "^18.18.8",
"@supabase/auth-helpers-nextjs": "^0.8.7",
"@supabase/auth-ui-react": "^0.4.5",
"@supabase/auth-ui-shared": "^0.1.7",
"@supabase/supabase-js": "^2.38.4",
```

Running TypeScript `"tsc --noEmit"` fails with:

```
node_modules/@supabase/gotrue-js/src/lib/helpers.ts:101:30 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(input: RequestInfo, init?: RequestInit | undefined): Promise<Response>', gave the following error.
    Argument of type 'string | URL | URL | Request | Request' is not assignable to parameter of type 'RequestInfo'.
      Type 'Request' is not assignable to type 'RequestInfo'.
        Property 'duplex' is missing in type 'Request' but required in type 'import("/Users/dowderek/projects/strokewise/node_modules/undici-types/fetch").Request'.
  Overload 2 of 2, '(input: URL | RequestInfo, init?: RequestInit | undefined): Promise<Response>', gave the following error.
    Argument of type 'string | URL | URL | Request | Request' is not assignable to parameter of type 'URL | RequestInfo'.
      Type 'Request' is not assignable to type 'URL | RequestInfo'.
        Property 'referrer' is missing in type 'import("/Users/dowderek/projects/strokewise/node_modules/undici-types/fetch").Request' but required in type 'Request'.

101   return (...args) => _fetch(...args)
                                 ~~~~~~~

  node_modules/undici-types/fetch.d.ts:154:12
    154   readonly duplex: RequestDuplex
                   ~~~~~~
    'duplex' is declared here.
  node_modules/typescript/lib/lib.dom.d.ts:18715:14
    18715     readonly referrer: string;
                       ~~~~~~~~
    'referrer' is declared here.


Found 1 error in node_modules/@supabase/gotrue-js/src/lib/helpers.ts:101
```

It appears that `@supabase/gotrue-js` is a dependency of `@supabase#supabase-js`. Going from "@types/node": "^18.16.13" -> "@types/node": "^18.18.8", causes the issue.

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Presumably with the same combination of packages I am using.

## Expected behavior

Supabase package types don't cause type errors.

## System information

MacOS with the following packages:

```
"typescript": "^5.0.4",
"supabase": "^1.99.5",
"@types/node": "^20.8.10",
"@supabase/auth-helpers-nextjs": "^0.8.1",
"@supabase/auth-ui-react": "^0.4.5",
"@supabase/auth-ui-shared": "^0.1.7",
"@supabase/supabase-js": "^2.36.0",
```

**Comment by derekdowling** [comment]
Going from `"@types/node": "^18.16.13"` -> `"@types/node": "^18.18.8",` appears to cause the issue.

**Comment by DeanWard** [comment]
I'm seeing this too. Does anyone know if there is a workaround?

**Comment by DeanWard** [comment]
I'm seeing this with a brand new project. Is there a version I can downgrade to to get around this issue?

**Comment by otopba** [comment]
I have the same issue:


```log
./node_modules/@supabase/gotrue-js/src/lib/helpers.ts:101:30
Type error: No overload matches this call.
  Overload 1 of 2, '(input: RequestInfo, init?: RequestInit | undefined): Promise<Response>', gave the following error.
    Argument of type 'string | Request | URL | URL | Request' is not assignable to parameter of type 'RequestInfo'.
      Type 'Request' is not assignable to type 'RequestInfo'.
        Property 'duplex' is missing in type 'Request' but required in type 'import("/Users/otopba/it/fameflow/fameflow-web/node_modules/undici-types/fetch").Request'.
  Overload 2 of 2, '(input: URL | RequestInfo, init?: RequestInit | undefined): Promise<Response>', gave the following error.
    Argument of type 'string | Request | URL | URL | Request' is not assignable to parameter of type 'URL | RequestInfo'.
      Type 'Request' is not assignable to type 'URL | RequestInfo'.
        Property 'referrer' is missing in type 'import("/Users/otopba/it/fameflow/fameflow-web/node_modules/undici-types/fetch").Request' but required in type 'Request'.

   99 |     _fetch = fetch
  100 |   }
> 101 |   return (...args) => _fetch(...args)
      |                              ^
  102 | }
  103 |
  104 | export const looksLikeFetchResponse = (maybeResponse: unknown): maybeResponse is Response => {

```

**Comment by satishgoml** [comment]
Any updates on this

**Comment by westmantech** [comment]
Same, cannot get a new project to work.

**Comment by danielwii** [comment]
I'm using this in package.json to ignore it temporarily:
```json
"resolutions": {
  "undici-types": "https://registry.yarnpkg.com/@favware/skip-dependency/-/skip-dependency-1.2.1.tgz"
},
```
but https://github.com/favware/skip-dependency seems only designed to work with Yarn.

**Comment by hereAlexT** [comment]
I got this issue too.

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!

**Comment by therrou** [comment]
I'm still experiencing this:
```
node version: v20.11.1
node types version: "^18.16.13"
 "@supabase/supabase-js": "^2.45.4",
 
 
```
<img width="763" alt="Screenshot 2024-09-15 at 22 24 48" src="https://github.com/user-attachments/assets/8a257d40-4d46-4f1f-bffe-7fbe6aedb4ce">
