### ISSUE TITLE
Oak Server Edge Functions readme example doesn't work

### ISSUE THREAD

**Issue by wave-light** [supabase/supabase#19038]
# Improve documentation

## Link 

https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/oak-server/README.md

## Describe the problem

The example request doesn't show how to call one of the routes defined in [index.ts](https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/oak-server/index.ts)
The index.ts file has three routes defined:
- GET '/oak-server'
- POST '/oak-server/greet'
- GET '/oak-server/redirect'

However, the example only shows how to call the function itself:
```
  curl --location --request POST 'http://localhost:54321/functions/v1/oak-server' \
--header 'Authorization: Bearer YOUR_TOKEN' \
--header 'Content-Type: application/json' \
--data-raw '{ "name": "John Doe" }'
```
This does not work, as it doesn't call the `/oak-server/greet` route defined in [index.ts](https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/oak-server/index.ts).
Furthermore, if I call `http://localhost:54321/functions/v1/oak-server/greet`, I get a 404 not found response.

## Describe the improvement

Describe how to call one of the routes defined in [index.ts](https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/oak-server/index.ts)

## Additional context

When running locally, extra url segments after the function name seem to be ignored, so for example http://localhost:54321/functions/v1/oak-server/some-route would igore the `/some-route` segment. If this is so, how can Oak Server work with Supabase functions?

**Comment by Akash187** [comment]
@wave-light looks like the issue is fixed and we can close this issue.

**Comment by wave-light** [comment]
@Akash187 there is still an issue with the docs showing the wrong endpoint to call. I've created a PR to update the docs: https://github.com/supabase/supabase/pull/19103
