### ISSUE TITLE
Error: PRIMARY KEY (version) schema_migrations after one remote migration

### ISSUE THREAD

**Issue by eleijonmarck** [supabase/supabase#20405]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I initiated supabase as a project
```
supabase init
```
```sh
supabase start
```
```sh
supabase db pull
```

```
supabase link --project-ref <ref>
```

Make some changes remote

```
(2) ~/dev/planpal on master [!] took 13s
1 % supabase migrations list
Connecting to remote database...


        LOCAL      │     REMOTE     │     TIME (UTC)
  ─────────────────┼────────────────┼──────────────────────
    20240113172750 │ 20240113172750 │ 2024-01-13 17:27:50

(base)
(2) ~/dev/planpal on master [!]
%
```

```
(2) ~/dev/planpal on master [!]
% supabase migrations up
Connecting to local database...
Applying migration 20240113172750_remote_schema.sql...
ERROR: multiple primary keys for table "schema_migrations" are not allowed (SQLSTATE 42P16)
At statement 27: ALTER TABLE ONLY "supabase_migrations"."schema_migrations"
    ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("version")
Try rerunning the command with --debug to troubleshoot the error.
```

## Expected behavior

That the remote migration is applied to my local database

**Comment by eleijonmarck** [comment]
I can fix it by modiying the remote db migration by the following:

```sql
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE SCHEMA IF NOT EXISTS "supabase_migrations";

ALTER SCHEMA "supabase_migrations" OWNER TO "postgres";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "supabase_migrations"."schema_migrations" (
    "version" text NOT NULL,
    "statements" text[],
    "name" text
);

ALTER TABLE "supabase_migrations"."schema_migrations" OWNER TO "postgres";

-- ALTER TABLE ONLY "supabase_migrations"."schema_migrations"
--     ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("version");

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
```

**Comment by pangolingo** [comment]
I am also seeing this error.
In my case I have make some changes on the remote db and run `supabase db pull` to pull down a new migration file that I can apply to my local db.

**Comment by wertania** [comment]
I have the same problem when I try to apply my remote db to local.

**Comment by CernyMatej** [comment]
What changes did you make to fix the error? I have the same problem.

**Comment by pangolingo** [comment]
> What changes did you make to fix the error? I have the same problem.

I fixed it by commenting out these lines in one of my migration files:

```
ALTER TABLE ONLY "supabase_migrations"."schema_migrations"
ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("version");
```

**Comment by logicminds** [comment]
Does this fix the problem or just remove the error?  It doesn't look like there is a primary key assigned in the initial table creation so maybe it is getting one by default.

```
CREATE TABLE IF NOT EXISTS "supabase_migrations"."schema_migrations" (
    "version" "text" NOT NULL,
    "statements" "text"[],
    "name" "text"
);
```

I would think we just need to alert the table creation like so and remove the alert statement causing the issue

```
CREATE TABLE IF NOT EXISTS "supabase_migrations"."schema_migrations" (
    "version" "text" NOT NULL PRIMARY KEY,
    "statements" "text"[],
    "name" "text"
);
```

**Comment by red2678** [comment]
I am also experiencing this. I tried setting the primary key during table creation, and I agree that should be the fix, but the initial remote scheme migration still fails with the multiple primary keys error (for me, anyway). For now, I am also just commenting it out.

**Comment by sweatybridge** [comment]
Closing as fixed. For anyone still running into it, rerun db pull should fix it.

**Comment by alexgshaw** [comment]
> > What changes did you make to fix the error? I have the same problem.
> 
> I fixed it by commenting out these lines in one of my migration files:
> 
> ```
> ALTER TABLE ONLY "supabase_migrations"."schema_migrations"
> ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("version");
> ```

Is this a safe fix? I'm now running into this issue in my existing project.

Supabase 1.172.2

**Comment by sweatybridge** [comment]
Yes, `supabase_migrations` schema is managed by supabase and don't need to be modified by any migration file. It used to appear in db diff but we have since excluded it.
