### ISSUE TITLE
Impersonation feature does not correctly impersonate the session_user

### ISSUE THREAD

**Issue by point-source** [supabase/supabase#20452]
# Bug report

- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 
- [x] I confirm this is a bug with Supabase, not with my own application. 

## Describe the bug

When impersonating a user via the studio's impersonation feature, the `session_user` returns "postgres" instead of "authenticator". This is an issue for things such as database functions which may depend on this value to determine whether the function is being called by an authenticated user vs a service key from the backend, etc.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Initialize a local supabase project
2. Create a function which just passes through the `session_user` value:
```sql
CREATE FUNCTION get_session_user() RETURNS text AS $$
BEGIN
    RETURN session_user;
END;
$$ LANGUAGE plpgsql SECURITY INVOKER;
```
3. Call the function in the SQL editor: `select get_session_user();`
4. Observe that it outputs "postgres"
5. Create a new user:
```bash
curl -X POST 'http://localhost:54321/auth/v1/signup' \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0" \
-H "Content-Type: application/json" \
-d '{"email": "devuser@email.local","password": "MyPassword", "email_confirm": true}'
```
6. Call the function in the SQL editor while impersonating the new user in the studio
7. Observe that it outputs "postgres"
8. Call the api to sign in as that user and retrieve a JWT:
```bash
curl -X POST "http://localhost:54321/auth/v1/token?grant_type=password" \
-H "Content-Type: application/json" \
-d '{"email": "devuser@email.local","password": "MyPassword"}'
```
9. Use the api to call the "get_session_user()" function:
```bash
curl "http://localhost:54321/rest/v1/rpc/get_session_user" -H "Authorization: Bearer users_jwt_token"
```
10. Observe that it outputs "authenticator"

## Expected behavior

Impersonating a user should fully impersonate/simulate all requests/actions performed by that user, including the value of the session_user.

## System information

- OS: macOS 14.2.1 (23C71)
- Browser: Firefox, Vivaldi

## Additional context

It would be really great if the supabase cli or studio made it easier to fetch a jwt for a specific user for the purposes of external impersonation.

EDIT: This is somewhat similar to [this issue](https://github.com/supabase/supabase/issues/10470) so there may be context on this other issue that is relevant here.

**Comment by rafeautie** [comment]
I'm also seeing an issue with impersonation locally with GraphiQL. The user_id column here is non-nullable because it has a default value of auth.uid() which is returning null when using graphiql. Making the same request from my application ui works as expected.

![image](https://github.com/supabase/supabase/assets/45886348/94cd0cdb-1800-4486-a3fd-1b4f5365e8d0)

**Comment by phishy** [comment]
It should also call any custom hooks to get metadata that is used inside functions, yes?

**Comment by point-source** [comment]
As this is currently blocking an issue on my project, is there a better way to determine whether a function is being called by an authenticated user vs an edge function or another db function than using `session_user`?

**Comment by Hallidayo** [comment]
Hi all, Just checking in here did you manage to resolve this one?

**Comment by point-source** [comment]
I don't believe this was resolved. I ended up working around it but I'm still unclear what the session_user variable ought to be used for and in what ways it can or can't be relied on. I was initially using it because @burggraf was using it in his scripts. I believe he still does.

**Comment by Hallidayo** [comment]
Hi @point-source - Sorry for the delay in getting back to you and thanks for the above. I'll close this one for now but I'll reopen if other users are still having the issue.
