### ISSUE TITLE
Add user blocked by Content Security Policy in Docker environments on studio:20240205-b145c86

### ISSUE THREAD

**Issue by argotechnica** [supabase/supabase#21476]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running Supabase locally (e.g. for local dev) using Docker, Auth > Add user functionality is blocked with error "Failed to create user: An error has occurred: NetworkError when attempting to fetch resource" (on Firefox) or "Failed to create user: An error has occurred: Failed to fetch" (on Chrome).

Console logs show, e.g.:
```
Refused to connect to 'http://localhost:54321/auth/v1/admin/users' because it violates the following Content Security Policy directive: "default-src 'self'  http://localhost:8000 http://localhost:8000 https://*.supabase.co wss://*.supabase.co https://*.hcaptcha.com https://cdn-global.configcat.com https://*.stripe.com https://*.stripe.network https://www.cloudflare.com https://1.1.1.1 https://*.vercel-insights.com https://api.github.com https://raw.githubusercontent.com". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

Refused to connect to 'http://localhost:54321/auth/v1/admin/users' because it violates the document's Content Security Policy.
```

At the same time, no logging appears in Docker logs to help troubleshoot further.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Do a fresh install of supabase@1.143.0 or later, which includes `supabase/studio:20240205-b145c86`
2. Try to create a new user (Supabase Studio > Authentication > Users > Add user > Create new user)

## Expected behavior

A new user is inserted. Docker logs look like this when the action is successful; note the IP address 172.21.0.1 due to use of a Docker environment:

```bash
$ docker logs supabase_kong_app_name

172.21.0.1 - - [23/Feb/2024:04:16:15 +0000] "OPTIONS /auth/v1/admin/users HTTP/1.1" 200 0 "http://localhost:54323/project/default/auth/users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
172.21.0.1 - - [23/Feb/2024:04:16:15 +0000] "POST /auth/v1/admin/users HTTP/1.1" 200 818 "http://localhost:54323/project/default/auth/users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

$ docker logs supabase_auth_app_name

{"component":"api","level":"info","method":"POST","msg":"request started","path":"/admin/users","referer":"http://localhost:54323/project/default/auth/users","remote_addr":"172.21.0.1","time":"2024-02-23T04:16:15Z","timestamp":"2024-02-23T04:16:15Z"}
{"auth_event":{"action":"user_signedup","actor_id":"00000000-0000-0000-0000-000000000000","actor_username":"service_role","actor_via_sso":false,"log_type":"team","traits":{"user_email":"asdf@asdf.com","user_id":"13177b9c-1ab9-48c6-a5b8-b07459c1b230","user_phone":""}},"component":"api","duration":61538536,"level":"info","method":"POST","msg":"request completed","path":"/admin/users","referer":"http://localhost:54323/project/default/auth/users","remote_addr":"172.21.0.1","status":200,"time":"2024-02-23T04:16:15Z","timestamp":"2024-02-23T04:16:15Z"}
```

## Screenshots

![Screenshot 2024-02-22 192221](https://github.com/supabase/supabase/assets/7676223/57b95c89-1949-4e48-ab3d-7cb8dc2498e1)
![Screenshot 2024-02-22 213823](https://github.com/supabase/supabase/assets/7676223/29231b57-785c-4a08-be29-c03834ede105)

## System information

- OS: Ubuntu 22.04.4 LTS on 5.15.133.1-microsoft-standard-WSL2 on Windows 11 Pro 23H2 22631.3155
- Browser (if applies): Firefox and Chrome
- Version of supabase-js: 2.39.2
- Version of Node.js: v18.17.1
- Version of supabase: 1.143.0 and later
- Version of supabase/studio: 20240205-b145c86
- Version of Docker: Docker version 25.0.3, build 4debf41

## Additional context

I run Supabase in Docker for local dev, then deploy to hosted Supabase environments. I started encountering an error with creating new users via Studio that seems to have hit a lot of other people; see especially https://github.com/supabase/supabase/issues/20985. I had the same error messages and console logs as in that issue (also shared above). Yet I found no logging via Docker logs, even after brute-forcing log monitoring with e.g.:
```bash
docker ps -q | xargs -L 1 -P `docker ps | wc -l` docker logs --since 30s -f
```
None of the recommendations from the 6 or so other GH issues were helping me either: I tried removing triggers from `auth.users`, clearing storage and cache, different browsers, playing with `.env` variables... Finally, I tested specific version releases of the `supabase` package in my own setup until I found the version at which this functionality broke.

I found that `supabase` v1.142.1 was the last version that worked for my setup, and it seems the only change introduced by the following version v1.143.0 was to bump `supabase/studio:20240101-8e4a094` to `supabase/studio:20240205-b145c86`. I've tested other versions of `supabase` including the latest (v1.147.0) and it seems all subsequent versions are broken.

I found that just rolling back `supabase` package to v1.142.1 was enough to resolve the issue locally (`npm install supabase@1.142.1 --save-dev`).

Looking at the working debug, my understanding is that `kong` routes to `auth`, thus if `kong` isn't even being hit in the non-working versions of `studio`, my assumption is that `studio` is filtering out some requests first via the Content Security Policy. Anyway the logging shows that in a Docker environment, a typical IP address can be e.g. 172.21.0.1, rather than 127.0.0.1. I don't have any suggestions for fixing this, but I would suggest to start looking at how `studio` is understanding Docker networking.

**Comment by encima** [comment]
Thanks for opening this! 
Will check with the team what changed between v1.142.1 and v1.143.0.
To confirm, you are running this via docker-compose and not using supabase-cli, right?

**Comment by argotechnica** [comment]
Thanks, and sorry for being unsure how to answer your question. I am building a Next.js app, using `package.json` to manage dependencies. I'm installing with e.g. `npm install supabase@1.142.1 --save-dev` and running Supabase with e.g. `npm run supabase:start`, which in turn runs this from `package.json`:

```
"scripts": {
    "dev": "next dev -p 8888",
    ...
    "supabase:start": "supabase start --workdir ./",
```

I have not used docker-compose to build/customize my own containers, nor do I use Docker commands to directly start or stop the containers, just `npm run supabase` etc.

**Comment by garmeeh** [comment]
Also seeing add user blocked locally. To confirm I deleted all images/volumes etc and started fresh.

Output and video if useful:

```bash
npx supabase --version
1.145.4
```


```bash
npx supabase start
15.1.0.147: Pulling from supabase/postgres
dae58cbd668a: Pull complete
40729def8a4f: Pull complete
866ca088feb7: Pull complete
88c1126fb705: Pull complete
e152d60a0289: Pull complete
2fcab1c3e37a: Pull complete
e046a3233c1d: Pull complete
ac9b924c8fa0: Pull complete
96ebec1f41b9: Pull complete
18b53e8cae46: Pull complete
9130071f6ccb: Pull complete
bae757ba9256: Pull complete
57f04a8fbe32: Pull complete
6f545b997ec3: Pull complete
b0555bc444cf: Pull complete
54de10b0a4a9: Pull complete
cbd752a595f6: Pull complete
c33c6e964a68: Pull complete
a598e7cdb605: Pull complete
d47edc8c8622: Pull complete
4077cac58935: Pull complete
2725b5778204: Pull complete
71abaebab41f: Pull complete
5140251ac7fe: Pull complete
Digest: sha256:5a8cb2e4acf7845a50e557bff8dcfb3e3c73b410e66c3cd011105fc09d8ff13b
Status: Downloaded newer image for public.ecr.aws/supabase/postgres:15.1.0.147
v0.46.4: Pulling from supabase/storage-api
c30352492317: Pull complete
eb7895eb72c1: Pull complete
7049a133eb54: Pull complete
90577567f13c: Pull complete
93e11a8d655a: Pull complete
46d43e942070: Pull complete
87d05ea306d0: Pull complete
29891eeb528d: Pull complete
24250a9fc06e: Pull complete
Digest: sha256:3aed9cc6df7c0e8060d1bf7dafc15edb085e68cc158a3dbe966be6ca5ac0d726
Status: Downloaded newer image for public.ecr.aws/supabase/storage-api:v0.46.4
v2.132.3: Pulling from supabase/gotrue
b8180c93b172: Pull complete
896f7a45b28c: Pull complete
f601026daa99: Pull complete
3fd170a1e9e8: Pull complete
6e3acd8bfe40: Pull complete
61462962e623: Pull complete
Digest: sha256:1bfae25acead513fbd459679a08463a1fc679769e6586c773cfc32d26c5b6dcf
Status: Downloaded newer image for public.ecr.aws/supabase/gotrue:v2.132.3
Seeding data supabase/seed.sql...
2.8.1: Pulling from supabase/kong
9b18e9b68314: Pull complete
7fd91e922960: Pull complete
450997ae687c: Pull complete
d8380bfcbd9b: Pull complete
Digest: sha256:1b53405d8680a09d6f44494b7990bf7da2ea43f84a258c59717d4539abf09f6d
Status: Downloaded newer image for public.ecr.aws/supabase/kong:2.8.1
3.0.3: Pulling from supabase/inbucket
f97344484467: Pull complete
c93cd632d565: Pull complete
7cadd1efbbe6: Pull complete
9853c0941218: Pull complete
b6f6817b1d4a: Pull complete
c5c956c4e9fc: Pull complete
59cbfb43403a: Pull complete
9c842edb6049: Pull complete
Digest: sha256:dc912ab76de647ca2a363fe285515e512e964cf699166773f3c2c73f5e7f71c0
Status: Downloaded newer image for public.ecr.aws/supabase/inbucket:3.0.3
v2.25.50: Pulling from supabase/realtime
failed to display json stream: toomanyrequests: Rate exceeded
Retrying after 4s: public.ecr.aws/supabase/realtime:v2.25.50
v2.25.50: Pulling from supabase/realtime
66dbba0fb1b5: Pull complete
4166bd72e87a: Pull complete
5dd8dfaab4d9: Pull complete
07484305c37f: Pull complete
a29e87bf71ee: Pull complete
933c3bd59c23: Pull complete
9614f9b82227: Pull complete
3031aaa00e8d: Pull complete
2faab5f119c5: Pull complete
f54398b16e61: Pull complete
2ffe6f08fe84: Pull complete
0aa8ae17bf21: Pull complete
Digest: sha256:c54ae830834a0a31587c22045a6e6c6743b5f9335527a179681bef34ca03260b
Status: Downloaded newer image for public.ecr.aws/supabase/realtime:v2.25.50
v12.0.1: Pulling from supabase/postgrest
dae58cbd668a: Already exists
57ddf91c0651: Pull complete
1f62d4558cf3: Pull complete
Digest: sha256:1201a178615539c57d9d0458b1ca516b1e031abbb6baf9c2959557d99625cdd0
Status: Downloaded newer image for public.ecr.aws/supabase/postgrest:v12.0.1
v3.8.0: Pulling from supabase/imgproxy
df8e44b0463f: Pull complete
b0f1dd53d7c3: Pull complete
ead8ac122bf1: Pull complete
4667765ff03a: Pull complete
744485a3a3a9: Pull complete
8650da0c91b5: Pull complete
Digest: sha256:0facd355d50f3be665ebe674486f2b2e9cdaebd3f74404acd9b7fece2f661435
Status: Downloaded newer image for public.ecr.aws/supabase/imgproxy:v3.8.0
v1.36.1: Pulling from supabase/edge-runtime
f546e941f15b: Pull complete
b968130b4710: Pull complete
ca2d189d7af3: Pull complete
dd1917e49a96: Pull complete
5de9526ebb5d: Pull complete
a39d7dc3f788: Pull complete
Digest: sha256:e97b802ca9e1234f7a598d184c0de1dc086b1fdbbb685944eb5c1227f3fd0c4e
Status: Downloaded newer image for public.ecr.aws/supabase/edge-runtime:v1.36.1
v0.77.2: Pulling from supabase/postgres-meta
f546e941f15b: Already exists
06495e08993c: Pull complete
8f7f70c95d2f: Pull complete
250e515ba9d8: Pull complete
87c2f57477b2: Pull complete
a9db845078fd: Pull complete
7fada51dd304: Pull complete
8b8519bb20b4: Pull complete
9cd5da2c1bd1: Pull complete
742946c4d253: Pull complete
Digest: sha256:e093e4848a83c1339700ed03e671f3d4f8b1f4c32ea5b9f0d574fe0eeb5bda32
Status: Downloaded newer image for public.ecr.aws/supabase/postgres-meta:v0.77.2
20240205-b145c86: Pulling from supabase/studio
25d3892798f8: Pull complete
255c789ffd36: Pull complete
5f1183836ae9: Pull complete
18c2260d48d3: Pull complete
bc31943dfa9c: Pull complete
1abdfba645bb: Pull complete
22b0fe5c1ad3: Pull complete
1399aed617ad: Pull complete
1d036e7a953d: Pull complete
128853cc7d74: Pull complete
Digest: sha256:859d770ffd1418b1a698f95e578aaf6ea48a69669053b308aa50c2de8663993e
Status: Downloaded newer image for public.ecr.aws/supabase/studio:20240205-b145c86
Started supabase local development setup.

         API URL: http://127.0.0.1:54321
     GraphQL URL: http://127.0.0.1:54321/graphql/v1
          DB URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
      Studio URL: http://127.0.0.1:54323
    Inbucket URL: http://127.0.0.1:54324
      JWT secret: X
        anon key: X
service_role key: X
```


https://github.com/supabase/supabase/assets/13333582/68f3580f-240c-406e-815d-c53da26de97e

**Comment by argotechnica** [comment]
Good video capture @garmeeh  , that's exactly what I experience. Does it work again for you to roll back to 1.142.1? (`npm install supabase@1.142.1` etc.) All I would have to do after stopping Supabase, installing (downgrading to) 1.142.1, and starting Supabase, is do a CTRL+F5 refresh in Studio and it would start working again for me.

**Comment by argotechnica** [comment]
FWIW, here's working:

```bash
$ npm install supabase@1.142.1 --save-dev

...(stop/start Supabase here)...

$ npm ls|grep supabase && npm run supabase:version && docker ps -a|awk '{print $2}'
├── @supabase/auth-helpers-nextjs@0.8.7
├── @supabase/supabase-js@2.39.2
├── supabase@1.142.1

> supabase:version
> supabase --version

1.142.1

ID
public.ecr.aws/supabase/studio:20240101-8e4a094
public.ecr.aws/supabase/postgres-meta:v0.75.0
public.ecr.aws/supabase/edge-runtime:v1.33.5
public.ecr.aws/supabase/imgproxy:v3.8.0
public.ecr.aws/supabase/storage-api:v0.46.4
public.ecr.aws/supabase/postgrest:v12.0.1
public.ecr.aws/supabase/realtime:v2.25.50
public.ecr.aws/supabase/inbucket:3.0.3
public.ecr.aws/supabase/gotrue:v2.132.3
public.ecr.aws/supabase/kong:2.8.1
public.ecr.aws/supabase/postgres:15.1.0.147
```

not working:

```bash
$ npm install supabase@1.143.0 --save-dev

...(stop/start Supabase here)...

$ npm ls|grep supabase && npm run supabase:version && docker ps -a|awk '{print $2}'
├── @supabase/auth-helpers-nextjs@0.8.7
├── @supabase/supabase-js@2.39.2
├── supabase@1.143.0

> supabase:version
> supabase --version

1.143.0

ID
public.ecr.aws/supabase/studio:20240205-b145c86
public.ecr.aws/supabase/postgres-meta:v0.75.0
public.ecr.aws/supabase/edge-runtime:v1.33.5
public.ecr.aws/supabase/imgproxy:v3.8.0
public.ecr.aws/supabase/storage-api:v0.46.4
public.ecr.aws/supabase/postgrest:v12.0.1
public.ecr.aws/supabase/realtime:v2.25.50
public.ecr.aws/supabase/inbucket:3.0.3
public.ecr.aws/supabase/gotrue:v2.132.3
public.ecr.aws/supabase/kong:2.8.1
public.ecr.aws/supabase/postgres:15.1.0.147
```

The only difference is this:

`supabase/studio:20240101-8e4a094` --> `supabase/studio:20240205-b145c86`

**Comment by jacobcoro** [comment]
Bump. Same issue on a new build with latest sdk

**Comment by mitjans** [comment]
Experiencing the same issue with the same error (CSP) when uploading a file in storage.

**Comment by yulolimum** [comment]
Same experience as the video [posted here](https://github.com/supabase/supabase/issues/21476#issuecomment-1961217785).

@argotechnica 's reproduction with downgrade is also confirmed (no issues on 1.142.1). Here are the image versions:

| 1.142.1  (no issues)                                                                                                                           | 1.145.4  (CSP issue)                                                                                                                       |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| ![yulolimum-capture-2024-02-25--10-12-50](https://github.com/supabase/supabase/assets/1775841/06276195-73eb-445d-baa2-55a035f4e494) | ![yulolimum-capture-2024-02-25--10-18-40](https://github.com/supabase/supabase/assets/1775841/d1474f5e-f438-4841-8216-56e6e8c80ae3) |
|                                                                                                                                     |                                                                                                                                     |
|                                                                                                                                     |                                                                                                                                     |

**Comment by encima** [comment]
Thanks for commenting everyone, this has been raised to the frontend team and is being investigated. 

As some of you have suggested, the workaround now is to use the 1.142.1 image. We will post back when we have more info/a fix.

**Comment by marcandersson** [comment]
I'm having the same issue and downgrading worked perfectly fine.

**Comment by encima** [comment]
This has now been fixed in the latest release of the CLI/Docker images. Please comment here if versions at v1.148.6 and above cause the same issues.

If you are not running v1.148.6, please update and test before commenting.

**Comment by Maxim-Filimonov** [comment]
Looks like this bug is back with new version:

## Screenshots
![CleanShot 2024-07-13 at 23 48 31](https://github.com/user-attachments/assets/6adccf32-81e4-40e2-ac17-ebc190d052e0)

## System information

- OS: MacOS
- Browser Chrome
- Version of supabase-cli: 1.183.5
- Version of Node.js: v18.17.1

## Additional context

Docker images versions:
- public.ecr.aws/supabase/postgres:15.1.0.153
- public.ecr.aws/supabase/studio:20240701-05dfbec
- public.ecr.aws/supabase/postgres-meta:v0.83.2
- public.ecr.aws/supabase/edge-runtime:v1.54.10
- public.ecr.aws/supabase/imgproxy:v3.8.0
- public.ecr.aws/supabase/storage-api:v1.6.8
- public.ecr.aws/supabase/postgrest:v12.0.1
- public.ecr.aws/supabase/realtime:v2.29.15
- public.ecr.aws/supabase/inbucket:3.0.3
- public.ecr.aws/supabase/gotrue:v2.155.3
- public.ecr.aws/supabase/kong:2.8.1

**Comment by Yusuf55mi** [comment]
I also getting this error with supabase cli v1.187.10. I am unable to add users via auth page. OS: 1.6.17 ubuntu bionic.

**Comment by tiltmaster** [comment]
> This has now been fixed in the latest release of the CLI/Docker images. Please comment here if versions at v1.148.6 and above cause the same issues.
> 
> If you are not running v1.148.6, please update and test before commenting.
I can confirm I am getting the same error on the latest version 1.219.2, On server, i am fetching a video and serving it as 

```
new Response(mediaResponse.body, {
status: 200,
headers: {
"Content-Type": contentType ?? "application/octet-stream", // Dynamically set content type
"Content-Disposition": `inline; filename="${suggestedFilename}"`, // Suggest a filename based on media type
},
});
```

which was working fine up until recently it started to return an error of `Blocked script execution in {{URL}} because the document's frame is sandboxed and the 'allow-scripts' permission is not set." and Refused to load media from {{URL}} because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback. And i am genuinely confused as the video file is being downloaded and passed,  but the response isnt allowing it,
