### ISSUE TITLE
Windows 10 and 11 supabase link is not working properly after scoop update vom supabase 1.69.(?) to 1.172.2

### ISSUE THREAD

**Issue by flobr** [supabase/supabase#27124]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

At windows 10 and 11 supabase link is not working properly after scoop update vom supabase 1.69.(?) to 1.172.2 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Make sure you have upgraded supabase to Version 1.172.2 
2. Call supabase link
3. You will be prompted for your supabase remote postgres password. Provide it.
4. The password is not accepted. (The username is auto-selected but not postgres as expected but postgres.XXX with XXX = supabase project name instead):

$ supabase link
Selected project: XXX
Enter your database password (or leave blank to skip):
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=aws-0-eu-central-1.pooler.supabase.com user=postgres.XXX database=postgres`: failed SASL auth (invalid SCRAM server-final-message received from server)

With supabase version 1.69.X I confirmed that it worked. So it definitively changed meanwhile. I used cygwin and copy & pasted the password. Also the (really great) supase support confirmed that it does not work with windows 10 and powershell with copy & paste. Manually typing the password should work. 

There are 2 possible workarounds with either setting the environment variable SUPABASE_DB_PASSWORD (which I did not tested) and using the password parameter and leaving the password prompt empty (which I tested):

supabase link --password YYY
Selected project: XXX
Enter your database password (or leave blank to skip):
Finished supabase link. 

## Expected behavior

Providing the password when requested by the prompt should link the supabase remote database correctly.

## System information

- OS: Windows 10 & 11
- Cygwin or Powershell
- Version of supabase: 1.69.X (works), 1.172.2 (does not work)

**Comment by encima** [comment]
Hi @flobr,

This does indeed seem like a Windows bug. To add some clarifications to Step 4: the connection details configured are for connecting to your database using Supavisor (the connection pooler). You can check these settings under `Project Settings -> Database` within your project. Supavisor uses the format `user.project` to determine which database to connect to.

**Comment by flobr** [comment]
Hello @encima !
Thank you for checking the issue! 
In our project settings there is the format user.project . But this setting was not changed! In the old version it worked like a charm. In version 1.172.2 is stopped working.

**Comment by encima** [comment]
No worries! The bug itself is unrelated to the username format, I was just providing an explanation for the format. 
I will let the CLI team respond to the bug itself.

**Comment by flobr** [comment]
@encima Thank you for the explanation :)

**Comment by flobr** [comment]
@encima also updating the just released newest version v1.176.2 does not help

**Comment by georgebrianb** [comment]
It's the same on macos.
I wanted to link my local project to one in my account and it tries to use the `postgres` user instead of `postgres.<project-id>` leading to this error:
`Error: failed to connect to 'host=db.<project-id>.supabase.co user=postgres database=postgres': dial error (dial tcp [2a05:d014:1c06:5f0e:1b11:f5db:7ac5:6ec4]:6543: connect: connection refused)`

**Comment by encima** [comment]
v1.176.4. is the latest and should resolve this. 
Some users have reported that a local version of supabase (in the package.json) has been overriding it. 
Try this and report back please.

**Comment by flobr** [comment]
@encima thank you very much! I tested again with windows 11 and installed the newest version 1.76.10 and it is still not working. It is the very same error from my original report.

**Comment by encima** [comment]
thanks for confirming. do you have special characters in your password?

**Comment by flobr** [comment]
@encima it worked with the old version 1.69.? with the same password without any problem

**Comment by encima** [comment]
noted, can you confirm it still works with that version? The issue could be with the CLI or changes to Supavisor.

**Comment by flobr** [comment]
@encima i tested it with windows 10 before updating to 1.172.2 and there it worked fine., after update it broke.

**Comment by encima** [comment]
I cannot repro with the latest versions on Mac or Linux so I'll wait for someone from the CLI team to test/respond

**Comment by flobr** [comment]
@Hallidayo with the newest version of supabase everything works like a charm :)
