### ISSUE TITLE
Two-Factor Authentication Issue

### ISSUE THREAD

**Issue by tptkds** [supabase/supabase#27812]
### Discussed in https://github.com/orgs/supabase/discussions/27802

<div type='discussions-op-text'>

<sup>Originally posted by **tptkds** July  5, 2024</sup>
## Issue with Two-Factor Authentication

I am experiencing an issue with logging into my Supabase account. I have been logged out and prompted to enter a two-factor authentication code. However, I did not set up two-factor authentication on my account.

### URL
`https://supabase.com/dashboard/sign-in-mfa?category=dashboard_bug&error=server_error&error_description=sql%3A+Scan+error+on+column+index+14%2C+name+%22encrypted_password%22%3A+converting+NULL+to+string+is+unsupported&message=Error%3A+This+endpoint+requires+a+Bearer+token&returnTo=%2Fsupport%2Fnew&subject=Failed+to+retrieve+factors#error=server_error&error_description=sql%253A+Scan+error+on+column+index+14%252C+name+%2522encrypted_password%2522%253A+converting+NULL+to+string+is+unsupported`

### Error Message
**Additionally, I am seeing the following error message:** 
Failed to retrieve factors
Error: This endpoint requires a Bearer token

Try refreshing your browser, but if the issue persists, please reach out to us via support.

I have tried refreshing my browser, but the issue persists. When I click the "Contact support" button, it redirects me back to the login page instead of providing support options.

### Login Redirect URL
`https://supabase.com/dashboard/sign-in?category=dashboard_bug&subject=Failed+to+retrieve+factors&message=Error%3A+This+endpoint+requires+a+Bearer+token&returnTo=%2Fsupport%2Fnew`

### Screenshot
![image](https://github.com/supabase/supabase/assets/58039782/817e5f44-d471-4af1-a00f-9aac620f9bbf)
</div>

**Comment by andynvt** [comment]
me too

**Comment by Jaimitolol** [comment]
Same here

**Comment by njordulv** [comment]
same problem

**Comment by GaryAustin1** [comment]
If your signup attempt was yesterday you likely need to contact support.  Some were left in a bad state.

https://status.supabase.com/#past-incidents

support@supabase.io

**Comment by encima** [comment]
Is this still affecting people? Please let us know here and we will reopen

**Comment by tptkds** [comment]
> Is this still affecting people? Please let us know here and we will reopen

No, the issue has been resolved. Thank you.

**Comment by ourbit-au** [comment]
> Is this still affecting people? Please let us know here and we will reopen

All good for me! Thanks

**Comment by o1Suleyman** [comment]
> Is this still affecting people? Please let us know here and we will reopen

yes. I am still facing this issue as you can see in the attached image. This is using Github.

![Image](https://github.com/user-attachments/assets/73536ce4-c171-417b-b0e5-f385752ff805)

**Comment by o1Suleyman** [comment]
> same error for me :(

it resolved for me after a few days somehow. Try logging in on another device, that's all I got sorry

**Comment by skf-funzt** [comment]
Hello @encima 

Since the weekend I am facing the same issue using the GitHub authentication method. 
It alternates between the request for an 2FA token, which I can't provide/ and the error message posted in this thread.

No solution has worked so far. No different browsers or devices, resetting the browsers or waiting for it to solve on it's own. Opened two support tickets for each behaviour, but answer still.

Any other suggestion how I can access my dashboard?

**Comment by Luciferutkarsh** [comment]
Hello @encima

My Signup is failing here as well, Can you help me out here, a simple singup and login is failing.
I've tried different browsers as well, and the outcome is still similar.

<img width="657" height="518" alt="Image" src="https://github.com/user-attachments/assets/be1277f9-2d49-46bd-8137-c47faf1dd330" />

**Comment by encima** [comment]
> Hello @encima
> 
> My Signup is failing here as well, Can you help me out here, a simple singup and login is failing.
> I've tried different browsers as well, and the outcome is still similar.
> 
> <img width="657" height="518" alt="Image" src="https://github.com/user-attachments/assets/be1277f9-2d49-46bd-8137-c47faf1dd330" />
> 
> 

Hi @Luciferutkarsh 
It looks like the email confirmation step is failing. Have you opened a support ticket?

**Comment by Luciferutkarsh** [comment]
yes I have SU-328627
