### ISSUE TITLE
Docs: storage information is missing

### ISSUE THREAD

**Issue by a0m0rajab** [supabase/supabase#33157]
# Improve documentation

## Link 

https://supabase.com/docs/reference/cli/supabase-storage

## Describe the problem

The storage page is missing information on how to use storage etc. 
The information is available on the file on GitHub yet it's not in the page. 

## Describe the improvement

the related code: 

![Image](https://github.com/user-attachments/assets/2d9638cf-964e-4c8a-8577-becfc5d150a5)

https://github.com/supabase/supabase/blob/master/apps/docs/spec/cli_v1_commands.yaml

Helpful link: 
https://github.com/supabase/cli/issues/1388

**Comment by a0m0rajab** [comment]
add a copy/paste option in the UI to use the storage would be awesome

**Comment by a0m0rajab** [comment]
If you want to download the storage to specific folder you need to follow the next steps: 

- have supabase CLI 
- create a folder
- move inside the folder and use the next commands: 

```
supabase init
supabase link
supabase storage cp ss:/// . --recursive --experimental      
```

**Comment by charislam** [comment]
Thanks @a0m0rajab! The original issue is fixed now! https://supabase.com/docs/reference/cli/supabase-storage-rm

Do you mind putting any new requests in another issue? That way I can close this one and we can keep things separated and clear when someone comes back around to work on your new request 😄

**Comment by a0m0rajab** [comment]
@charislam thanks for triaging this, yet the original issue is not fixed yet. 

The problem here is that there is no example of how to use the codes which is the usage line: 

```
 supabase storage cp <src> <dst> [flags]
```

I am expecting to see this line somewhere in the docs. (which it's available in the codes) 

![Image](https://github.com/user-attachments/assets/24b30d36-32a1-4009-9736-969e86c12a8e)

maybe on the right side of the docs here.

**Comment by a0m0rajab** [comment]
You can notice the same behavior for the whole supabase storage docs, it seems like it's missing the implementation

**Comment by charislam** [comment]
Oh I see! Good call, I don't think we display that line at all, but it would indeed be a good addition. I'll reopen the issue!

**Comment by a0m0rajab** [comment]
yeah, it's a bit tricky, since it's written in the specs file but not shown in the docs.

**Comment by a0m0rajab** [comment]
thanks for reopening  this one.
