### ISSUE TITLE
Sending password recovery is erroring with property providers should not exist

### ISSUE THREAD

**Issue by silentworks** [supabase/supabase#33331]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to send a password recovery from the dashboard it is returning this error `property providers should not exist`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the [Authentication](https://supabase.com/dashboard/project/_/auth/users) section of the dashboard
2. Click on any user in the list
3. Scroll down to Reset password and click **Send password recovery**
4. See error `property providers should not exist` show up in the toast menu 
5. No email is sent due to the error

## Expected behavior

No error should be showing up and the password recovery should send an email

## Screenshots

https://github.com/user-attachments/assets/22a7a56c-ddd7-4e2b-81e6-d365e6c60161

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by sk0le** [comment]
I have the same problem.

Following to keep up with the issue.

**Comment by ranlopez** [comment]
Same problem here. I have custom SMTP set up.

**Comment by santivdt** [comment]
Same problem

**Comment by jindalsumit1991** [comment]
Same problem

**Comment by ismaelguerrib** [comment]
Same problem

**Comment by Johnislost** [comment]
Same with resend SMPT

**Comment by SIDIboulmartoub-spec** [comment]
same

**Comment by codebyphani** [comment]
I am facing the same issue!

**Comment by joshenlim** [comment]
Hey everyone! Sorry about this one - but we've just pushed a fix out for this:
https://github.com/supabase/supabase/pull/33352

Could y'all try once more to see if its now resolved on your end? 🙏

**Comment by caphilldev** [comment]
I am having the same problem as well. It worked for a while, but now the error is occurring.

**Comment by chrisdueck** [comment]
This is still happening for me when clicking `Send password recovery`:

![Image](https://github.com/user-attachments/assets/ebc83dd7-cf05-4c39-b0a7-bd8311d87bcc)
