### ISSUE TITLE
Error (invalid algorithm) when trying to upload files to storage with Clerk third party auth

### ISSUE THREAD

**Issue by d-stoll** [supabase/supabase#34948]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to upload files to a supabase storage bucket which is secured by a policy using Clerk Third party auth, I receive the following error:

`{"statusCode":"403","error":"Unauthorized","message":"invalid algorithm"}`

The RLS policy is the following:

`((bucket_id = '<bucket_id>'::text) AND (( SELECT (auth.jwt() ->> 'sub'::text)) = (storage.foldername(name))[1]))`

The policy has been working since we migrated to third party auth with Clerk using auth.jwt() everywhere, but broke today with the above error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup an instance with Clerk third party auth
2. Setup a storage bucket
3. Add the following policy to secure the bucket: `((bucket_id = '<bucket_id>'::text) AND (( SELECT (auth.jwt() ->> 'sub'::text)) = (storage.foldername(name))[1]))`
4. Try to upload an object to the storage with path "<bucket_id>/<user_id>/example.pdf" with supabase-js using the Clerk session token as access token
5. See error

## Expected behavior

The object should be uploaded without error.

## System information

- OS: Windows
- Browser: chrome
- Version of supabase-js: 2.49.4
- Version of Bun: 1.2.4

**Comment by hyper-lode** [comment]
I'm having the exact same issue, started only in the past 12 hours

**Comment by szilard-n** [comment]
I’m having the exact same issue.

**Comment by wahibonae** [comment]
exact same issue

**Comment by GaryAustin1** [comment]
https://status.supabase.com/incidents/98c41745c964

**Comment by itslenny** [comment]
The incident impacting Clerk integration (and most 3rd party auth using storage) has been resolved. It was caused by a change that went in to production yesterday. The fix for it has now been deployed in all regions and this problem should be resolved.

**Comment by d-stoll** [comment]
Fix works on our side 👍🏼

**Comment by skynth** [comment]
Hey! I'm still experiencing this issue, is there something I need to do to make sure the change goes into effect? Also doing Supabase Clerk integration.

**Comment by skynth** [comment]
To add more detail here, it works on our production environment but not on our local environment. Could it be an issue with with how clerk development mode integrates with our local supabase environment?

> Hey! I'm still experiencing this issue, is there something I need to do to make sure the change goes into effect? Also doing Supabase Clerk integration.

**Comment by naufalafif** [comment]
If you are using clerk integration in supabase, you might wanna try configured clerk jwt template. it works in my case
though i still found other issue, createSignedUrl not working properly (JWTMalformed).

**Comment by capeflow** [comment]
> To add more detail here, it works on our production environment but not on our local environment. Could it be an issue with with how clerk development mode integrates with our local supabase environment?

Can confirm that this is also happening for me specifically with Clerk Development Mode - any news on another look at this sub-issue?

**Comment by pedroresende** [comment]
@d-stoll Any news about this ? I'm asking because I'm unable to upload files for authenticated users.

**Comment by d-stoll** [comment]
@pedroresende The fix they implemented back then worked for us. We have since migrated away from supabase so I can't be of any help anymore unfortunately.
