### ISSUE TITLE
Issue with email confirmations on sign up

### ISSUE THREAD

**Issue by Stoozy** [supabase/supabase#37610]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Trying to sign up users with email confirmation enabled doesn't actually send the email confirmation anymore (it was working fine before for me).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable email confirmation in Authentication > Sign In / Providers > Confirm Email
2. Make a basic signUp call like so:

```javascript
      const { data, error} = await supabase.auth.signUp({
        email: formData.email,
        password: formData.password
      });
```

## Expected behavior

It should send a sign up confirmation email before returning session data.

Also, #[37573](https://github.com/supabase/supabase/pull/37573) may be relevant?

## System information

- OS: Windows
- Version of supabase-js: ^2.49.4
- Version of Node.js: v22.14.0

**Comment by silentworks** [comment]
This should be fixed now https://github.com/supabase/supabase/pull/37615. Can you test this on your side and see if it's working a report back on this issue.

**Comment by Stoozy** [comment]
It's still not working for me.

<img width="381" height="252" alt="Image" src="https://github.com/user-attachments/assets/fdcbabf5-2944-454a-b066-8168d3ae2353" />

**Comment by Stoozy** [comment]
Browser had old code cached, did a hard reload and it's working again. Thanks
