### ISSUE TITLE
Window.location.href is undefined on react-native

### ISSUE THREAD

**Issue by theking465** [supabase/supabase#3790]
# Bug report

## Describe the bug

When creating a new project using Expo-cli react-native and setting it up with a simple Supabase database, it crashes when building on Android. It runs fine on web version. The underlying issue is I believe with the goTrue.js library which takes window.location.href as argument but on mobile devices window.location is undefined see screenshot.

## To Reproduce

Setup a new Expo project and install Supabase using the following client setup

```import { createClient } from '@supabase/supabase-js'
import AsyncStorage from '@react-native-async-storage/async-storage'
import {REACT_APP_SUPABASE_URL, REACT_APP_SUPABASE_ANON_KEY} from "@env";

const supabaseUrl = REACT_APP_SUPABASE_URL
const supabaseAnonKey = REACT_APP_SUPABASE_ANON_KEY

console.log(supabaseUrl, supabaseAnonKey)
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
	localStorage: AsyncStorage
  })
 ```
Run it using `expo start` and connect expo to an android device

## Expected behavior

The project builds succesfully

## Screenshots

![afbeelding](https://user-images.githubusercontent.com/9497296/140391696-77133649-b19d-4f37-9435-013930c23251.png)

## System information

- OS: Windows + WSL
- Version of supabase-js: 1.25.2
- Expo version: 42.0.1
- Version of Node.js: v14.17.4

**Comment by kiwicopple** [comment]
this should now be fixed with this update: https://github.com/supabase/gotrue-js/pull/153

**Comment by DeabitTech** [comment]
excusme, but i have already the same issue, is not fixed @kiwicopple in the row 724 of GoTrueClient.js i can see the assignment: `window.location.href = url` 

please can you help me?

**Comment by nrowley** [comment]
same this bug persists in new v2 when using signInWithOAuth in expo RN

**Comment by DeabitTech** [comment]
Yeah, @kiwicopple please can you fix It?

**Comment by tomsoderlund** [comment]
Having this problem too in Supabase.js 2.0.4 and Expo/React Native.

**Comment by hf** [comment]
Hey everyone, this is now being tracked here: https://github.com/supabase/gotrue-js/issues/495

The team is pressed for time at this time and is not able to pick this up, but we'll help out with merging a PR if you're able to fix it.

**Comment by gustavodiasobtrader** [comment]
I'm also having this problem in RN using the signInWithOAuth function

**Comment by kushmishraa** [comment]
still not fixed facing the issue in 2024 .
