### ISSUE TITLE
Detailed error messages when queries from SQL Editor fail

### ISSUE THREAD

**Issue by emschwartz** [supabase/supabase#461]
# Feature request

## Is your feature request related to a problem? Please describe.

If a query fails when run from the SQL editor, it shows the message `Error: failed to run query. Bad request`.

## Describe the solution you'd like

 It would be useful if it could show additional error details in the error popup or somewhere else in the UI.

## Describe alternatives you've considered

Alternatively, it could just log the additional details in the JS console.

**Comment by awalias** [comment]
fixed

**Comment by lustremedia** [comment]
This is not FIXED! 

I just ran into an issue on the SQL editor saying:

**structure of query does not match function result type**  while creating a function! It said nothing else ...

I was looking for answers on the web but could not find any on that particular problem set, only more specifics in the **details** of the error message.

The details of the error message however was never shown, I finally, after 2 hours of searching, found the details of the error message in the response type of the request in the web console (F12)

User experience was not the best here ... and I wasted 3 hours of my time!

**Comment by awalias** [comment]
hey @lustremedia feel free to open a new feature request here for `more detailed error messages when debugging SQL functions`: https://github.com/supabase/supabase/issues/461#issuecomment-1972762254

be sure to add details about the error message that you found in the console that was not propogated to the output box on the SQL editor and the frontend team will take a look at it. thanks!

**Comment by lustremedia** [comment]
@awalias Thanks for reaching out, I hope my frustration did not come across to harsh :/

That is all it showed:
![image](https://github.com/supabase/supabase/assets/1240374/c3e48cfb-5c68-4f1a-8c36-fc33b8e3aa54)

This is what I found later and was of course an easy fix, but took me a while ...
![image](https://github.com/supabase/supabase/assets/1240374/85c93c34-e3c9-4c96-ab1b-971e7ba3b89a)

**Comment by awalias** [comment]
ok yeah I'll reopen this one - it's close enough :)

**Comment by joshenlim** [comment]
hey there @lustremedia! this should now be fixed - i'm not sure if i'm able to reproduce exactly what you ran into, but I can verify that the dashboard will show the detailed errors from the query
<img width="934" alt="image" src="https://github.com/supabase/supabase/assets/19742402/74f66fb9-e2ca-4b2c-a7f6-a874bc918605">

I'll go ahead to close this issue but please do let us know otherwise! If you might still be facing this issue, do help us by providing us some steps to reproduce the issue that you're running into 🙏
