### ISSUE TITLE
Realtime does not emit all events

### ISSUE THREAD

**Issue by danieldaeschle** [supabase/supabase#5290]
# Bug report

## Describe the bug

In the network tab the websocket message comes in. But the event handler does not work properly. Sometimes it works and sometimes the listener won't get called.

## To Reproduce

It's very hard to reproduce and I don't know how to debug it because it only appears sometimes. I can't descibe it properly.
My code is this:

```
useEffect(() => {
    if (!selectedProfile) {
      return () => {};
    }
    const todayMinus15Days = new Date();
    todayMinus15Days.setDate(todayMinus15Days.getDate() - 15);

    supabase
      .from<{ count: number; user_id: string }>('counts')
      .select('count')
      .eq('user_id', selectedProfile!)
      .then(({ data }) => {
        const counts = data ?? [];
        if (counts.length === 1) {
          const first = counts[0].count;
          setCount(first);
        } else {
          supabase
            .from('counts')
            .insert({ count: 0, user_id: selectedProfile })
            .then();
        }
      });

    supabase
      .from('rules')
      .select()
      .eq('user_id', selectedProfile)
      .order('points')
      .then(({ data }) => setRules(data ?? []));

    supabase
      .from('events')
      .select()
      .order('created_at', { ascending: false })
      .eq('user_id', selectedProfile)
      .gt('created_at', todayMinus15Days.toISOString())
      .then(({ data }) => setEvents(data ?? []));

    supabase
      .from('profiles')
      .select()
      .then(({ data }) =>
        setProfiles((data ?? []).filter((p) => !!p.first_name)),
      );

    const updateSubscription = supabase
      .from('*')
      .on('INSERT', (payload) => {
        if (payload.new.user_id !== selectedProfile) {
          return;
        }
        switch (payload.table) {
          case 'rules': {
            setRules((rules) => [...rules, payload.new]);
            break;
          }
          case 'events': {
            setEvents((events) => {
              const newEvents = [...events, payload.new];
              newEvents.sort(
                (a, b) =>
                  new Date(b.created_at).getTime() -
                  new Date(a.created_at).getTime(),
              );
              return newEvents;
            });
            break;
          }
          case 'counts': {
            setCount(payload.new.count);
            break;
          }
        }
      })
      .on('DELETE', (payload) => {
        switch (payload.table) {
          case 'rules': {
            setRules((rules) =>
              rules.filter((rule) => rule.id !== payload.old.id),
            );
            break;
          }
          case 'events': {
            setEvents((events) =>
              events.filter((event) => event.id !== payload.old.id),
            );
            break;
          }
        }
      })
      .on('UPDATE', (payload) => {
        if (payload.new.user_id !== selectedProfile) {
          return;
        }
        switch (payload.table) {
          case 'rules': {
            setRules((rules) => {
              const idx = rules.findIndex((rule) => rule.id === payload.old.id);
              const newRules = [...rules];
              newRules[idx] = payload.new;
              return newRules;
            });
            break;
          }
          case 'events': {
            setEvents((events) => {
              const idx = events.findIndex(
                (event) => event.id === payload.old.id,
              );
              const newEvents = [...rules];
              newEvents[idx] = payload.new;
              return newEvents;
            });
            break;
          }
          case 'counts': {
            setCount(payload.new.count);
            break;
          }
        }
      })
      .subscribe();

    return () => {
      updateSubscription.unsubscribe();
    };
  }, [selectedProfile]);
```

## Expected behavior

It should work always...

## System information

- OS: Android; Windows
- Browser (if applies) chrome
- Version of supabase-js: 1.29.2
- Version of Node.js: 16

**Comment by w3b6x9** [comment]
@danieldaeschle `supabase-js` v1.29.2 enforces unique subscriptions and there may be some weirdness with just calling `unsubscribe()` during cleanup. Make sure you're using `removeSubscription` or `removeAllSubscriptions` to properly clean up the subscription on unmount:

```js
supabase.removeSubscription(updateSubscription)
```

**Comment by GaryAustin1** [comment]
@danieldaeschle Besides, w3b6x9 suggestion, you can put an error handler in subscribe like:

.subscribe((status)=>{console.log('subscribe status = ',status);})

And see if subscription is stable.

Also are you seeing just one webworker, or several after awhile?  If you lose connection you would have a new webworker for each reconnect, but still a "good" subscription if you don't look at status, as it retries during breaks (but does not track data during break) an reconnects.

**Comment by danieldaeschle** [comment]
I did what @w3b6x9 said. But the problem still exists :/

**Comment by w3b6x9** [comment]
@danieldaeschle is there a specific change you're not getting? for example, is it only updates that you're sometimes not getting? or is it all changes?

can you try again and invoke `supabase.getSubscriptions()` and take a look at the subscriptions?

**Comment by danieldaeschle** [comment]
It's only sometimes and totally random. But it happens very often. When it happens I just reload the page and then it works again.

**Comment by w3b6x9** [comment]
@danieldaeschle you mentioned:

> In the network tab the websocket message comes in

if you check again do you have several connections or just one? just trying to ascertain if the connection is constantly trying to reconnect.

can you also version bump to the latest `supabase-js`?

**Comment by danieldaeschle** [comment]
I have two connections btw.

**Comment by w3b6x9** [comment]
@danieldaeschle can you check if both of them are actively receiving messages or only one of them? do both connections have outgoing 'heartbeat' messages?

**Comment by w3b6x9** [comment]
@danieldaeschle also, can you please provide screenshots of the network tab if you're willing? just want to make sure i get all relevant info.

**Comment by ryan-richards** [comment]
> 
Currently experiencing the same issue. Get a subscribed status but often wont receive changes until browser is refreshed.

**Comment by danieldaeschle** [comment]
Yes, I have the problem mainly on mobile device. If I go back to the app and then a update should come it it no longer works.

**Comment by GaryAustin1** [comment]
@danieldaeschle is it Android/Chrome?  I was setting this test up to check mobile environments as they seem flaky.  Chrome/Edge have the background problem with realtime on any device, but it is "only" lost data during reconnects. 

In reading Android power saving spec, it implies they shut off the internet connection on sleeping tabs.  If so realtime will go into a mode of retrying with longer and longer timeout periods.  If that is happening, then when you come back to the tab it could be awhile before it retries again depending how long tab was gone.

I hope to verify this soon, but was setting up this test to do that and this other problem side tracked me...

**Comment by danieldaeschle** [comment]
Android/Chrome yes.

I need to implement a indicator if the connection is on. Then I see it better.

**Comment by w3b6x9** [comment]
@danieldaeschle i just released a fix. can you please see if `supabase-js` v1.30.4 addresses your issue?

**Comment by w3b6x9** [comment]
@danieldaeschle closing this issue. feel free to reopen if v1.30.4 does not address your issue.

**Comment by danieldaeschle** [comment]
It did not solve it. But I don't want to solve the issue anymore.

**Comment by w3b6x9** [comment]
@danieldaeschle will close this issue. Feel free to reopen if you want to investigate again.
