### ISSUE TITLE
Edge Functions require CORS headers in order to be called with function.js

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#6267]
# Bug report
Using function.js invoke to call a Edge Function generates CORS errors.

## To Reproduce

Invoke the sample hello function using Supabase.js function.invoke() call.

## Expected behavior
It appears a critical part of the process has been left out in generating functions in the examples.
As a quick test I modified the example return to add Access Control Headers
```
 return new Response(
    JSON.stringify(data),
    { 
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST",
        "Access-Control-Expose-Headers": "Content-Length, X-JSON",
        "Access-Control-Allow-Headers": "apikey, X-Client-Info, Content-Type, Authorization, Accept, Accept-Language, X-Authorization",
      }
      },
  );
```
With this set of headers the Edge Function worked.
EDIT it worked with fetch... to work with invoke() I had to add apikey and X-Client-Info

I have not parsed the exact headers, but just did a quick copy from the web searching for CORS errors.

There might be a better way.

## Screenshots
Before the headers:
![image](https://user-images.githubusercontent.com/54564956/161389424-83620af5-d53e-49de-91d6-a9be8967a237.png)
After the headers:
![image](https://user-images.githubusercontent.com/54564956/161389554-e861745e-fda0-4c72-abac-23a8a1e8592a.png)

## System information
Latest Edge Functions Examples
Latest supabase.js

**Comment by GaryAustin1** [comment]
The above was tested using javascript fetch as I'm having another issue with the body format on functions.invoke()...
Going back to invoke and still getting CORS error.. I suspect some more header info needs to be added to the above...

**Comment by GaryAustin1** [comment]
After a bit of trial and error.  You have to handle the preflight request (OPTIONS) and the POST request as two different calls for browser calls with function.js.

This is the code I ended up with:
```
import { serve } from "https://deno.land/std@0.131.0/http/server.ts";

console.log("Hello from Functions!");

serve(async (req) => {
        console.log(req.method)
        if (req.method === 'OPTIONS') {
            return new Response(
                'ok',
                {
                    headers: {
                        "Access-Control-Allow-Origin": "*",
                        "Access-Control-Allow-Methods": "POST",
                        "Access-Control-Expose-Headers": "Content-Length, X-JSON",
                        "Access-Control-Allow-Headers": "apikey,X-Client-Info, Content-Type, Authorization, Accept, Accept-Language, X-Authorization",
                    }
                }
            );
        }
        else {
            const jsonData = await req.json();
            const name = jsonData.name;
            const data = {message: `Hello there ${name}!`};
            return new Response(
                JSON.stringify(data),
                {
                    headers: {
                        "Content-Type": "application/json",
                        "Access-Control-Allow-Origin": "*",
                        "Access-Control-Allow-Methods": "POST",
                        "Access-Control-Expose-Headers": "Content-Length, X-JSON",
                        "Access-Control-Allow-Headers": "apikey,X-Client-Info, Content-Type, Authorization, Accept, Accept-Language, X-Authorization",
                    }
                }
            );
        }
});
```

**Comment by inian** [comment]
Ah, we should have documented this. @thorwebdev can you add your CORS example to the repo?

Functions doesnt pass CORS headers to the client by default (like our other products). Since you control the server you can enable CORS if required. 

Probably we can add this as an option when you deploy functions to enable CORS by default so that it is easier to get started.

**Comment by GaryAustin1** [comment]
Others are encountering this also on Discord.
It sure would be nice if someone familiar with Deno uses an example with some of cors functions out there.  Seems a pain to have to do all our own headers, but I've not found the correct cors functionality to work with "serve" as in Thor's demo.

**Comment by GaryAustin1** [comment]
@inian It doesn't help that either the function.js code is not implemented correctly or the docs for invoke are wrong.

Passing in {body: {name:"cat"}} as shown in the invoke() api docs ALSO generates a CORS error with the sample code because function.js seems to want a string like body:'{"name":"cat"}'.
I've reported that error yesterday in function.js repository.

**Comment by thorwebdev** [comment]
@GaryAustin1 thanks so much for pointing this out!

Two things to hopefully help with this:

1. I've added a minimal CORS example: https://github.com/supabase/supabase/pull/6279/commits/50b5c341dca44caad26af6e0a711f3950d5c37e3
2. I've updated the docs to correctly reflect that body needs to be stringified: https://github.com/supabase/supabase/pull/6283/files

@inian @kiwicopple fyi, two more issues around this remain:

1. If you have a malformed body (or any other error before the function can be invoked) the function will return an error text but without any CORS headers, meaning in the browser it looks like a CORS error, while the actual error is related to malformed body.
```
FetchError: invalid json response body at https://gvkuljvaukfrwmrythfi.functions.supabase.co/select-from-table-with-auth-rls reason: Unexpected token I in JSON at position 0
```
2. When serving a function locally the CORS error persists, because the preflight OPTIONS request returns a 404.
![image](https://user-images.githubusercontent.com/5748289/161471494-d1101710-bc47-43d3-a8ae-cf9558b73760.png)

**Comment by thorwebdev** [comment]
Okay, closing this out as these should all be addressed now. @GaryAustin1 please let me know if you think I've missed anything.

**Comment by riderx** [comment]
Hey @thorwebdev i still have the issue on my side, it doesn't look to repond the headers i have set

**Comment by riderx** [comment]
i tried the same function in 2 projects, and it works on second one, it seems it link to other issue : https://github.com/supabase/supabase/issues/6829

**Comment by magicseth** [comment]
This makes it very hard to get started using functions from the browser. A simple demo would be great here.

**Comment by thorwebdev** [comment]
@magicseth have you seen https://github.com/supabase/supabase/tree/master/examples/edge-functions/supabase/functions/browser-with-cors ? Is that what you're looking for?

**Comment by magicseth** [comment]
Yes I figured it out eventually. The frustrating part is that it is not in the [docs](https://supabase.com/docs/guides/functions) which say: 

> By default Edge Functions require a valid JWT to be send in the authorization header. This header is automatically set when invoking your function via a Supabase client library.

But make no mention of CORS. I assumed that JWT would make CORS work.

On top of that, once I had CORS working, another error made it seem as if I hadn't fixed the CORS issue, because it showed up in my browser a CORS issue.

I spent too many hours trying to figure out why it was not working.

As an aside, it would be nice to have an example of calling an edge function from the javascript client in that doc as well.

I figured it out, but a few tweaks to the docs will make the next person's path much simpler!

**Comment by thorwebdev** [comment]
Thanks for the feedback @magicseth ! We've added some details around CORS to the guide: https://supabase.com/docs/guides/functions#cors-cross-origin-resource-sharing. Thanks to you it will hopefully be easier for future users 💚  Thanks again for taking the time to note down your feedback and suggestions :)

**Comment by MartinMalinda** [comment]
You can also move the CORS logic to a higher order function.

```ts
const handleCORS = (cb: (req: any) => Promise<Response>) => {
  return async (req) => {
    if (req.method === 'OPTIONS') {
      return new Response('ok', { headers: corsHeaders })
    }

    const response = await cb(req);
    Object.entries(corsHeaders).forEach(([header, value]) => {
      response.headers.set(header, value);
    });

    return response;
  }
};
```

Then in your endpoint you just serve like this:
```ts
serve(handleCORS(async (req) => {
   return new Response(...)
});
```

**Comment by ajayvignesh01** [comment]
Does the options request count towards edge function invocation limit?

**Comment by ajayvignesh01** [comment]
Thanks for the clarification @laktek!

Was under the assumption that it did since the metrics tab counted 'OPTIONS' as an invocation, and the billing tab mentioned "sum of all invocations". Perhaps that could use some clarification?
<img width="1003" alt="Screenshot 2024-03-04 at 8 00 52 AM" src="https://github.com/supabase/supabase/assets/138313465/e32668b8-0ffb-4d1e-87f7-09c8fe6a0556">

**Comment by laktek** [comment]
@ajayvignesh01 Metrics tab does include all requests (include OPTIONS). But I can confirm the "sum of all invocations" in billing tab excludes the `OPTION` requests. The query / source used for billing is different from what's used in metrics tab.

**Comment by ajayvignesh01** [comment]
Thank you for clarifying that @laktek .

I think this PR should make it more clear for others as well https://github.com/supabase/supabase/pull/21739#issue-2166866694
