### ISSUE TITLE
Table editor: filter by booleans not working

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase#665]
# Bug report

## Describe the bug

In the table editor if you try to filter by boolean (column is true) it does not work. Also boolean column icons show as number.

Here is my filter
<img width="679" alt="Screen Shot 2021-02-02 at 9 47 44 PM" src="https://user-images.githubusercontent.com/6392501/106691124-f5539380-65a0-11eb-92e5-e04c4b136290.png">

Here is the column type
<img width="727" alt="Screen Shot 2021-02-02 at 9 48 00 PM" src="https://user-images.githubusercontent.com/6392501/106691140-fc7aa180-65a0-11eb-9b62-96663b88b30a.png">

Here is the table data after the filter is applied:
<img width="484" alt="Screen Shot 2021-02-02 at 9 47 50 PM" src="https://user-images.githubusercontent.com/6392501/106691150-01d7ec00-65a1-11eb-9fd7-ef89dd80aa03.png">

## To Reproduce

1. Create a table with a boolean as a column.
2. Set the value of the column to false
3. Filter by that column `is true`
4. See false columns still present

**Comment by kiwicopple** [comment]
Thnaks for the bug report @zlwaterfield - this one is now fixed 🚢 


https://user-images.githubusercontent.com/10214025/107936740-f2ec3300-6fbd-11eb-8f51-39265f089e36.mov

**Comment by shikhardadhich** [comment]
Still not working for-
  const { data: rows, error } = await supabase
        .from("citylist")
        .select("id, city, rates, created_at, is_active")
        .order("created_at",{ascending:false})
        .order('is_active');

this treat it as: 

select=id%2Ccity%2Crates%2Ccreated_at%2Cis_active&is_active=eq.true&order=created_at.desc

**Comment by gregnr** [comment]
@shikhardadhich thanks for reporting. Would you mind opening a new issue with this and we can debug there?
