### ISSUE TITLE
Understanding how to populate name of the user on DB

### ISSUE THREAD

**Issue by molimat** [supabase/supabase#681]
Hello guys, thank you for this awesome tool you've been creating.

I am developing a system that needs to save the name of the user. I am doing as it shows on this [nextjs example](https://github.com/vercel/nextjs-subscription-payments/blob/main/pages/signup.js).

It goes like this:
```
 const { error, user } = await signUp({ email, password });
    if (error) {
      setMessage({ type: 'error', content: error.message });
    } else {
      if (user) {
        await supabase
          .from('users')
          .update({
            full_name: name
          })
          .eq('id', user.id);
        setUser(user);
```

where the signUp follows exactly the docs. But I am get nothing from this. Neither user nor error returns anything. Checking the docs, I tried obtaining through the "data" deconstruction and I got the new user id, but when I try populating the database it shows me an error saying it cannot find the user id (however the row for this id is correctly created through triggers.) 

What is happening? Am I doing anything wrong?

Thank you for the help.

**Comment by kiwicopple** [comment]
Hey @molimat, I suspect you are running into this issue: https://github.com/supabase/gotrue-js/issues/45

Can you please try to "disable email confirmations" on your dashboard and see if that works?

![image](https://user-images.githubusercontent.com/10214025/107173758-8db7a100-6a03-11eb-999c-1e4d6c2479fa.png)

We should have this fixed soon.

**Comment by molimat** [comment]
Yes, it works after this change, but I don't want to disable the emails confirmation to avoid fake mails though. I will follow up the issue you mentioned. THanks.

**Comment by kiwicopple** [comment]
[This issue](https://github.com/supabase/gotrue-js/issues/45) is now fixed, so if you upgrade to supabase-js > v1.3.4 the `user` will always be returned, even with email confirmations turned on 👍

**Comment by molimat** [comment]
Yes, i saw it on the other issue but I think I am still getting some issue. My DB has a policy of only allowing the user to update him self, but as signUp() doesnt logIn the user, even when the user is returned from signUp() I can't update my users table. What should I do?

**Comment by kiwicopple** [comment]
> My DB has a policy of only allowing the user to update him self

In this case the only ways that I can personally think of:

- update the user with the service key (from a server-side function)
- create a `rpc()` function that circumvents the RLS policies, but has some other rules to make sure that only this user can update themself (but I don't know what those rules would be).
