### ISSUE TITLE
RLS not working with the slack clone example

### ISSUE THREAD

**Issue by city41** [supabase/supabase#810]
# Bug report

## Describe the bug

After setting up the slack clone example, RLS does not appear to be honored.

## To Reproduce

(these steps amount to "stand up the slack clone")

1. Create a new project in Supabase
2. In the SQL editor, choose the "slack clone" query and execute it.
3. clone this github repo and head to `examples/nextjs-slack-clone`
4. `yarn` to get dependencies installed
5. edit .env.local with the values found at settings/api in the dashboard. set `NEXT_PUBLIC_SUPABASE_URL` equal to the url in settings/api and `NEXT_PUBLIC_SUPABASE_KEY` equal to the public anon key in settings/api
6. edit `addMessage` in `lib/Store.js` as shown below
7. run the app with `yarn dev`
8. create an account and add a new message to a chat room

edit `addMessage` to look like this

```javascript
export const addMessage = async (message, channel_id, user_id) => {
  // set this equal to the uuid of the supabot user as found in your project's user table.
  user_id = '4eafa20e-3365-4895-b525-a44395d4202f';
  try {
    let { body } = await supabase.from('messages').insert([{ message, channel_id, user_id }])
    return body
  } catch (error) {
    console.log('error', error)
  }
}

```

## Expected behavior

The message should not be added because the insert RLS check on public.messages should prevent it due to `user_id` being that of supabot's and not the logged in user who actually created the message.

Actual behavior: the message is added, with a spoofed user_id.

## System information

- OS: Ubuntu 20
- Browser: Chrome
- Version of supabase-js: 1.4.2
- Version of Node.js: 12.20.0

## Additional context

There is a discussion about this [here](https://github.com/supabase/supabase/discussions/802) where @steve-chavez offered troubleshooting tips to try and figure out why RLS doesn't seem to be working.

**Comment by kiwicopple** [comment]
Sorry about that @city41. Looks like I forgot a "for select" statement here:

![image](https://user-images.githubusercontent.com/10214025/110199423-4e119700-7e93-11eb-879d-14c355adad14.png)


So the policy is evaluating to "for all". I fixed it in the readme and added the change to our dashboard (will be deployed ~monday)

**Comment by city41** [comment]
Ah interesting. Thanks for the fix. I'm a noob at Postgres and Supabase is causing me to get better at it, but still have a good ways to go.

I wonder if there's a way to write tests or some kind of automatic audit to confirm RLS is doing what you think it is. Having something like this slip through into production on an important site could be pretty bad.

**Comment by kiwicopple** [comment]
> I wonder if there's a way to write tests or some kind of automatic audit to confirm RLS is doing what you think it is.

Defintiely! You can use [pgTAP](https://pgtap.org/), or in this case we could have used Jest/Mocha, since the app is written in JS.

For this case, we didn't add testing because it's an example and we need the code to be small/simple/readable. Adding pgtap would be *another* thing for new-comers to get their head around

**Comment by steve-chavez** [comment]
@city41 For some sample pgtap tests, check: https://github.com/steve-chavez/socnet/blob/master/tests/comments.sql
