### ISSUE TITLE
redirectTo not respected when resetting password

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#832]
# Bug report

## Describe the bug

When sending a password reset email, the `redirectTo` option is ignored. Instead of a user being redirected to a specific place on the site (e.g., the password reset page), users are always redirected to the Site Url as specified in the Authentication Settings on the dashboard.

## To Reproduce

1. In the Supabase dashboard, go to Authentication > Settings, Make sure the site url is `https://example.com`
2. Send a password reset email. Make sure to specify the `redirectTo` parameter.

```js
supabase.auth.api.resetPasswordForEmail('hello@example.com', {
    redirectTo: `https://example.com/account/set-password`,
})
```

2. In your email, click on the password reset link
3. Error: you are redirected to `https://example.com`, not `https://example.com/account/set-password`

I've gotten the same results regardless of whether the `redirectTo` is the same domain as the Site Url in the Authentication Settings on the dashboard.

## Expected behavior

After clicking the password reset link, users are redirected to the url in the `redirectUrl`.

In this case, users are redirected to `https://example.com/account/set-password`

## System information

- OS: macOS 11.2
- Browser: Brave 1.21.73 on Chromium: 89.0.4389.72
- Version of supabase-js: 1.5.0
- Version of Node.js: 12.17.0

**Comment by Nick-Mazuk** [comment]
After a week of using other Supabase Auth functions, it seems like the `redirectTo` parameter isn't working on any functions, including `signUp` and `signIn`.

**Comment by PabloSzx** [comment]
> After a week of using other Supabase Auth functions, it seems like the `redirectTo` parameter isn't working on any functions, including `signUp` and `signIn`.

I can confirm it, this bug should be priority, since it basically kills the auth functionality, at first I though it was an issue with the "SITE URL" Config, since it says:

```
The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in emails.
```

But trying different combinations of "URL1,URL2" "URL1;URL2" "URL1 URL" and nothing works for like a "allow-list", but it seems to only be a single url, which doesn't make any sense

**Comment by kiwicopple** [comment]
Hey everyone, just an fyi we're trying to work with the Netlify team to make sure that we can get this into GoTrue. It's a fundamental shift in the server's set up so we are a bit slower. We will definitely solve this!

**Comment by kiwicopple** [comment]
I'm going to close this one now in favor of the gotrue-js issue: https://github.com/supabase/gotrue-js/issues/65

**Comment by FloCalvo** [comment]
I am having this issue, redirectTo is not working for me on password recovery, although it works fine for sign up. Is this supposed to be working?

**Comment by kangmingtay** [comment]
Hey @FloCalvo, yes it's supposed to be working, i've actually tried to reproduce the issue you're facing and it works fine for me. Could you kindly check if you have entered the exact url in the "Additional Redirect URLs" that you wish to redirect your users to?

**Comment by kangmingtay** [comment]
Hey @FloCalvo, @andresiggia resolved it by clearing the cache and restarting his app, hope this helps!

**Comment by pencilcheck** [comment]
redirectTo isn't respected in invite link when generating the link from the server (with service role key)

Will try to see if it is respected when sending password reset email

**Comment by pencilcheck** [comment]
Still doesn't really work, it acts randomly, I wonder why it hasn't been resolved more a year later??

**Comment by kangmingtay** [comment]
hey @pencilcheck, can you please reach out to us at our [support channel](https://app.supabase.com/support/new). This issue has been resolved already and it is difficult for us to help triage your problem without any reproducible steps.

**Comment by pencilcheck** [comment]
sure, just sent. but weird that if this is fixed why didn't it work? the use case is so simple, simply calling the API but it just doesn't do what it is suppose to.

**Comment by AgarwalPragy** [comment]
This issue is still there it seems?

```js
const { error: err } = await locals.supabase.auth.resetPasswordForEmail(body.email as string, {
  redirectTo: `${request.headers.get('host')}/reset-password/confirm`,
})
```

<img width="931" alt="image" src="https://user-images.githubusercontent.com/7423639/211942112-8f3462fa-517c-4316-9991-dbf01fd4f4cc.png">

Even after setting the `redirectTo` and configuring the redirect URLs in the app, the reset link sent to the email is 
```
https://sbrosumaqydwjndsxzxp.supabase.co/auth/v1/verify?token=8a0e5c70ce779b45d2423ffeb48d3482946120554092ffa85a02b87b&type=recovery&redirect_to=http://localhost:5173
```

Note that it redirects to `http://localhost:5173` and not `http://localhost:5173/reset-password/confirm`

**Comment by kangmingtay** [comment]
@AgarwalPragy Have you checked out [our guide](https://supabase.com/docs/guides/auth/overview#redirect-urls-and-wildcards) on redirect URLs yet? If you want to add `http://localhost:5173/reset-password/confirm` to the allow list, you should use a pattern like `http://localhost:5173/*/*` or `http://localhost:5173/**`. Note that the usage of `**` is more permissive since it ignores the `/` which is considered as a separator while `*` will respect it.

**Comment by AgarwalPragy** [comment]
@kangmingtay That didn't help either.

Supabase config
<img width="901" alt="image" src="https://user-images.githubusercontent.com/7423639/212441314-def427da-0774-40d6-ba0b-21145f9a11fd.png">

code
```typescript
console.log(`http://${request.headers.get('host')}/reset-password/set`)
const { error: err } = await locals.supabase.auth.resetPasswordForEmail(body.email as string, {
  redirectTo: `${request.headers.get('host')}/reset-password/set`,
})
```
console output
```
http://localhost:5173/reset-password/set
```

Reset link received in email  `...&type=recovery&redirect_to=http://localhost:5173`
```
https://sbrosumaqydwjndsxzxp.supabase.co/auth/v1/verify?token=24e1d8bbe5c058fc17783e636080a8001aaf06d832a4c827c0fd8f3e&type=recovery&redirect_to=http://localhost:5173
```

**Comment by AgarwalPragy** [comment]
Turns out, it doesn't work if the `redirectTo` value is missing the protocol.

**Comment by GorvGoyl** [comment]
@AgarwalPragy  that fixed the issue. This seems like bad DX. Either protocol should be required for all redirectTo URLs or none.

**Comment by carmenlop** [comment]
I was able to fix this by updating the href in the email template to add /reset-password/confirm at the end of the url
hacky, but it works

**Comment by kangmingtay** [comment]
@carmenlop that works because the `redirectTo` query param is the last param in the email link returned which is not guaranteed to be the case in the future -  if you aren't able to redirect the user correctly, it could mean that your allow list is not set up right. Have you checked out [our guide](https://supabase.com/docs/guides/auth#redirect-urls-and-wildcards) on setting up redirect URLs yet?

**Comment by scosman** [comment]
For anyone having this issue with the UI helpers, there was a bug causing the same symptoms described above. Be sure to update you packages, specifically `@supabase/auth-ui-svelte`

**Comment by mwoss** [comment]
Also, remember to add your redirect URLs to the `Redirect URLs` list on the `Authentication > URL Configuration` page. Otherwise, your users will be automatically redirected to default `Site URL`.

**Comment by rohanpatelg** [comment]
Still not working for me. Does it worked for you guys? If yes, can you tell me how?

**Comment by jordanshardy** [comment]
Bump

**Comment by adamchenwei** [comment]
> Also, remember to add your redirect URLs to the `Redirect URLs` list on the `Authentication > URL Configuration` page. Otherwise, your users will be automatically redirected to default `Site URL`.

Can confirm, this is the issue. right after I added localhost link into the URL Configuration, it works for the new reset password email. you will see the url get reflected. Thank you @mwoss

**Comment by oouazize** [comment]
I am facing the issue of being redirected to the default SITE_URL in self-hosted Supabase, even when the redirect URL is listed in ADDITIONAL_REDIRECT_URLS. When will this be fixed?

**Comment by seva3l** [comment]
Hello guys i'm also facing they same issue on my expo app where it should be redirected into my app using custom scheme.

i have redirect url like this. com.myapp://** but when i inspect element the email sent. the href is incorrect
![image](https://github.com/user-attachments/assets/49408d14-a4d2-4646-a85b-15dc118f875b)

**Comment by zhyd1997** [comment]
> Turns out, it doesn't work if the `redirectTo` value is missing the protocol.

Thanks! It works for me when handling multi-tenancy workspaces!

**Comment by fatmazumrutyilmaz** [comment]
Hi guys,

I'm also facing this issue. My SITE_URL is "http://localhost:4200/" and my Redirect URLs list includes "http://localhost:4200/**". However, I couldn't redirect to "http://localhost:4200/resetpassword". Will this issue be fixed?

**Comment by bilguun1130** [comment]
Not sure why is this closed, when the issue persists. Has anyone found a solution yet?

**Comment by f-z-coder** [comment]
this isssue occur on localhost also

**Comment by kangarko** [comment]
For me, the issue was with Supabase's URL configuration. Even though I correctly set the redirectTo URL in code, Supabase was overriding it.

We needed to configure the redirect URL in your Supabase project settings:

1. Go to the Supabase dashboard (https://app.supabase.com)
2. Select your project
3. Go to Authentication → URL Configuration
4. Update the Site URL to match your production domain: https://yoursite.com
5. Add https://yoursite.com/your-reset-password-link to the Redirect URLs list

**Comment by mike-ayres** [comment]
This is working for us without wildcards.

I originally tried basic regex: `http://localhost:port/*` but that didn't work. It apparently [uses glob patterns](https://pkg.go.dev/github.com/gobwas/glob#Compile) instead of `* means anything`, and it looked like `**` would match any sequence of characters, but that also did not work.

So I went back to entering in all the urls one-at-a-time. :/

**Comment by samuba** [comment]
Can confirm wildcards not working in the Redirect URLs for both `*` and `**`. 
When adding the entire password reset url it works.
